//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Role } from './Role';
import { AvdelingType } from './AvdelingType';

export interface Department
{
	id: number;
	institusjonId: number;
	avdelingTypeId: number;
	navn: string;
	roller: Role[];
	avdelingType: AvdelingType;
}
