//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface BeskyttelsesutstyrOversiktRapport
{
	utstyrsnavn: string;
	incorrectTypes: string[];
	wasUsed: boolean;
	wasUsedCorrectly: boolean;
	isRequired: boolean;
	comment: string;
}
