//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { FourIndicationsObservation } from './FourIndicationsObservation';
import { Sesjon } from './Sesjon';

export interface FourIndicationsSession extends Sesjon<FourIndicationsObservation>
{
}
