//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export abstract class HandJewelryTypeConstants
{
	public static AllClear: string = `ALL_CLEAR`;
	public static Ring: string = `RING`;
	public static WatchBracelet: string = `WATCH_BRACELET`;
	public static LongNails: string = `LONG_NAILS`;
	public static ArtificialNailsShellac: string = `ARTIFICIAL_NAILS_SHELLAC`;
	public static ShortSleeved: string = `SHORT_SLEEVED`;
	public static LongSleeved: string = `LONG_SLEEVED`;
}
