//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Observation } from './Observation';
import { HanskeMedIndikasjonType } from './HanskeMedIndikasjonType';
import { HanskeUtenIndikasjonType } from './HanskeUtenIndikasjonType';
import { HandHygieneAfterGloveUseType } from './HandHygieneAfterGloveUseType';

export interface HanskeObservasjon extends Observation
{
	hanskeMedIndikasjonTyper?: HanskeMedIndikasjonType[];
	hanskeUtenIndikasjonTyper?: HanskeUtenIndikasjonType[];
	gloveUsed: boolean;
	handHygieneAfterGloveUseType?: HandHygieneAfterGloveUseType;
}
