//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { RegionalHealthcareOrganization } from './RegionalHealthcareOrganization';

export interface HealthcareOrganization
{
	id: number;
	name: string;
	regionaltHealthcareOrganizationId: number;
	regionalHealthcareOrganization: RegionalHealthcareOrganization;
}