//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Department } from './Department';
import { InstitusjonType } from './InstitusjonType';
import { Region } from './Region';
import { Municipality } from './Municipality';
import { Helseforetak } from './Helseforetak';

export interface Institution
{
	id: number;
	navn: string;
	forkortelse: string;
	herId: string;
	departments: Department[];
	institusjontype: InstitusjonType;
	region: Region;
	kommune: Municipality;
	harObservasjoner: boolean;
	helseforetak: Helseforetak;
}
