//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Role } from './Role';
import { IndikasjonType } from './IndikasjonType';
import { Activity } from './Activity';
import { HandsmykkeType } from './HandsmykkeType';
import { ProtectiveEquipmentOverviewReport } from './ProtectiveEquipmentOverviewReport';
import { HanskeObservasjon } from './HanskeObservasjon';
import { ProtectiveEquipmentObservation } from './ProtectiveEquipmentObservation';

export interface ObservasjonOversiktRapport
{
	id: any;
	role: Role;
	comment: string;
	registrerttidspunkt: any;
	indikasjonstyper: IndikasjonType[];
	activity: Activity;
	handsmykketyper: HandsmykkeType[];
	beskyttelsesutstyrsetting: string;
	beskyttelsesutstyr: ProtectiveEquipmentOverviewReport[];
	hanskeObservasjon: HanskeObservasjon;
	beskyttelsesutstyrObservasjon: ProtectiveEquipmentObservation;
}
