//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Role } from './Role';

export interface Observasjon
{
	id: string;
	role: Role;
	registrerttidspunkt?: Date;
	sesjonId: string;
	kommentar?: string;
}
