//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Role } from './Role';

export interface OppdaterAvdelingRequest
{
	id: number;
	name: string;
	avdelingTypeId: number;
	roles: Role[];
}
