//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Observasjon } from './Observasjon';
import { ProtectiveEquipment } from './ProtectiveEquipment';
import { ProtectiveEquipmentSettingType } from './ProtectiveEquipmentSettingType';

export interface ProtectiveEquipmentObservation extends Observasjon
{
	beskyttelsesutstyrliste: ProtectiveEquipment[];
	settingtype: ProtectiveEquipmentSettingType;
}
