//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { SessionType } from './SessionType';

export interface SesjonRapport
{
	id: string;
	avdelingsnavn: string;
	startTime: any;
	type: SessionType;
	institutionsName: string;
	isSelected?: boolean;
}
