//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Department } from './Department';
import { ObservationOverviewReport } from './ObservationOverviewReport';

export interface SesjonOversiktRapport
{
	id: any;
	type: string;
	observatorNavn: string;
	department: Department;
	startTime: any;
	createdTime: any;
	comment: string;
	overforingstatus: any;
	observations: ObservationOverviewReport[];
	isSelected: boolean;
}
