//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum SessionType {
	FireIndikasjoner = 1,
	InnUt = 2,
	Handsmykker = 3,
	Gloves = 4,
	ProtectiveEquipment = 5,
	IkkeValgt = 6
}
