//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum SessionType {
	FourIndications = 1,
	InOut = 2,
	HandJewelry = 3,
	Gloves = 4,
	ProtectiveEquipment = 5,
	NotSelected = 6
}
