//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Department } from './Department';

export interface Session<TObservation>
{
	id: string;
	department: Department;
	startTime: Date;
	observations?: TObservation[];
	institutionsName?: string;
	institutionId?: number;
	comment?: string;
}
