export class UrlPaths {
  static homePage = 'homepage';
  static observations = 'fhiadmin/observations';
  static observationsDepartment = 'fhiadmin/observations/department';
  static transferSessions = 'coordinator/transfer';
  static editingByInstitutions = 'fhiadmin/institutions';
  static editingByCodeworks = 'fhiadmin/codeworks';
  static editingofhandjewelrytypes = 'fhiadmin/typesofhandjewelry';
  static editingOfDepartments = 'coordinator/departments';
  static editingByClinics = 'coordinator/clinics';
  static editingByCoordinators = 'coordinator/coordinators';
  static editingByObservers = 'coordinator/observers';
  static editingPredefinedComments = 'coordinator/predefinedcomments';
  static profile = 'profile';
  static changeInstitution = 'changeinstitution';
  static institutions = 'fhiadmin/institutions';
  static fhiAdminOverview = 'fhiadmin/overview';
  static request = 'coordinator/request';
  static healthcareOrganization = 'fhiadmin/healthcareOrganization';
  static email = 'fhiadmin/email';
  static reports = 'coordinator/reports';
  static fiveIndicationsCompliance = 'fiveindications/compliance';
  static fiveIndicationsCompliancePdf = 'fiveindications/compliance-five-indications-pdf';
  static handjewelryCompliancePdf = 'handjewelry/compliance-handjewelry-pdf';
  static downloadExcel = 'regular-reports/departmentalreport';
}
