
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "HyFive.fullname" . }}-oidc
  labels:
    {{- include "HyFive.labels" . | nindent 4 }}
type: Opaque
stringData:
  OpenIdConnect__AuthUse: "{{ default .Values.oidc.auth_use "true" }}"
  OpenIdConnect__Authority: "{{ .Values.oidc.authority }}"
  OpenIdConnect__ClientId: "{{ .Values.oidc.client_id }}"
  OpenIdConnect__ClientSecret: "{{ .Values.oidc.client_secret }}"
  ClaimTypes__RoleClaimType: "{{ .Values.oidc.claims.role }}"
  ClaimTypes__EnvironmentAccessClaimType: "{{ .Values.oidc.claims.env_access }}"
  ClaimTypes__DisplayNameClaimType: "{{ .Values.oidc.claims.display_name }}"
  ClaimTypes__UniqueIdentifierClaimType: "{{ .Values.oidc.claims.unique_id }}"
  Security__EnvironmentAccess: "{{ .Values.oidc.environment_name }}"
