export class Urls {
  static LoginsideUrl = '';
  static StartsideForObservasjonUrl = 'registrering';
  static RegistrereFireIndikasjonerUrl = 'registrering/fire-indikasjoner';
  static RegistrereHandsmykkerUrl = 'registrering/handJewelry';
  static RegistrereHanskeUrl = 'registrering/hanske';
  static RegistrereBeskyttelsesutstyrUrl = 'registrering/protectiveEquipment';
  static IkkeSendteSesjonerUrl = 'sessions/ikke-sendte';
  static SendteSesjonerUrl = 'sessions/sendte';
  static FireIndikasjonerSesjonUrl = 'sessions/fire-indikasjoner';
  static HandsmykkeSesjonUrl = 'sessions/handJewelry';
  static HanskeSesjonUrl = 'sessions/hanske';
  static BeskyttelsesutstyrSesjonUrl = 'sessions/protectiveEquipment';
  static SendteFireIndikasjonerSesjonUrl = 'sessions/sendte/fire-indikasjoner';
  static SendteHandsmykkeSesjonUrl = 'sessions/sendte/handJewelry';
  static SendteHanskeSesjonUrl = 'sessions/sendte/hanske';
  static SendteBeskyttelsesutstyrSesjonUrl = 'sessions/sendte/protectiveEquipment';
  static ProfilUrl = 'profil';
}
