// <auto-generated />
using System;
using HyFive.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HyFive.DataAccess.Migrations
{
    [DbContext(typeof(HandHygieneContext))]
    partial class HandhygieneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DepartmentClinic", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("ClinicId")
                        .HasColumnType("integer");

                    b.HasKey("DepartmentId", "ClinicId");

                    b.HasIndex("ClinicId");

                    b.ToTable("DepartmentClinic");
                });

            modelBuilder.Entity("DepartmentRole", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("DepartmentId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("DepartmentRole");
                });

            modelBuilder.Entity("ProtectiveEquipmentMisuseType", b =>
                {
                    b.Property<int>("ProtectiveEquipmentId")
                        .HasColumnType("integer");

                    b.Property<int>("MisuseTypesId")
                        .HasColumnType("integer");

                    b.HasKey("ProtectiveEquipmentId", "MisuseTypesId");

                    b.HasIndex("MisuseTypesId");

                    b.ToTable("ProtectiveEquipmentMisuseType");
                });

            modelBuilder.Entity("FourIndicationsObservationIndicationType", b =>
                {
                    b.Property<int>("IndicationTypesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservationsId")
                        .HasColumnType("uuid");

                    b.HasKey("IndicationTypesId", "ObservationsId");

                    b.HasIndex("ObservationsId");

                    b.ToTable("FourIndicationsObservationIndicationType");
                });

            modelBuilder.Entity("HandJewelryObservationHandJewelryType", b =>
                {
                    b.Property<int>("HandJewelryId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservationsId")
                        .HasColumnType("uuid");

                    b.HasKey("HandJewelryId", "ObservationsId");

                    b.HasIndex("ObservationsId");

                    b.ToTable("HandJewelryObservationHandJewelryType");
                });

            modelBuilder.Entity("GloveWithIndicationTypeGloveObservation", b =>
                {
                    b.Property<int>("GloveWithIndicationTypesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservationsId")
                        .HasColumnType("uuid");

                    b.HasKey("GloveWithIndicationTypesId", "ObservationsId");

                    b.HasIndex("ObservationsId");

                    b.ToTable("GloveWithIndicationTypeGloveObservation");
                });

            modelBuilder.Entity("GloveObservationWithoutIndicationType", b =>
                {
                    b.Property<int>("GloveWithoutIndicationTypesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservationsId")
                        .HasColumnType("uuid");

                    b.HasKey("GloveWithoutIndicationTypesId", "ObservationsId");

                    b.HasIndex("ObservationsId");

                    b.ToTable("GloveObservationWithoutIndicationType");
                });

            modelBuilder.Entity("HyFive.Domain.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HPRNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IdentityPseudonym")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HPRNumber");

                    b.HasIndex("IdentityPseudonym");

                    b.HasIndex("InstitutionId");

                    b.ToTable("User");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HyFive.Domain.User.UserAccessRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProcessedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessedByUsername")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HPRNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IdentityPseudonym")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("UserAccessRequest");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityTypeId")
                        .HasColumnType("integer");

                    b.Property<bool?>("UsedGloves")
                        .HasColumnType("boolean");

                    b.Property<int>("SecondsUsed")
                        .HasColumnType("integer");

                    b.Property<bool>("TimingWasPerformed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("ActivityType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ProtectiveEquipmentObservationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasUsed")
                        .HasColumnType("boolean");

                    b.Property<bool>("WasUsedCorrectly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIndicated")
                        .HasColumnType("boolean");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("EquipmentTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProtectiveEquipmentObservationId");

                    b.HasIndex("EquipmentTypeId");

                    b.ToTable("ProtectiveEquipment");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProtectiveEquipmentSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int?>("SettingTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProtectiveEquipmentSessionId");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("RegistrationTime");

                    b.HasIndex("RoleId");

                    b.HasIndex("SettingTypeId");

                    b.ToTable("ProtectiveEquipmentObservation");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("ProtectiveEquipmentType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentSettingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("ProtectiveEquipmentSettingType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentSettingTypeProtectiveEquipmentType", b =>
                {
                    b.Property<int>("ProtectiveEquipmentTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ProtectiveEquipmentSettingTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDefaultIndicated")
                        .HasColumnType("boolean");

                    b.HasKey("ProtectiveEquipmentTypeId", "ProtectiveEquipmentSettingTypeId");

                    b.HasIndex("ProtectiveEquipmentSettingTypeId");

                    b.ToTable("ProtectiveEquipmentSettingTypeProtectiveEquipmentType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.MisuseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProtectiveEquipmentTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProtectiveEquipmentTypeId");

                    b.HasIndex("Name");

                    b.ToTable("MisuseType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.FourIndicationsObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FourIndicationsSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("FourIndicationsSessionId");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("RegistrationTime");

                    b.HasIndex("RoleId");

                    b.ToTable("FourIndicationsObservation");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.HandJewelryObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HandJewelrySessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HandJewelrySessionId");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("RegistrationTime");

                    b.HasIndex("RoleId");

                    b.ToTable("HandJewelryObservation");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.HandJewelryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("HandJewelryType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Gloves.HandHygieneAfterGloveUseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("HandHygieneAfterGloveUseType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Gloves.GloveWithIndicationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("GloveWithIndicationType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Gloves.GloveObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("UsedGloves")
                        .HasColumnType("boolean");

                    b.Property<int?>("HandHygieneAfterGloveUseTypeId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GloveSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HandHygieneAfterGloveUseTypeId");

                    b.HasIndex("GloveSessionId");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("RegistrationTime");

                    b.HasIndex("RoleId");

                    b.ToTable("GloveObservation");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Gloves.GloveWithoutIndicationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("GloveWithoutIndicationType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.IndicationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Number")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("IndicationType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("HyFive.Domain.Session.TransferStatusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("TransferStatusType");
                });

            modelBuilder.Entity("HyFive.Domain.Session.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("ObservatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TransferStatusTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Discriminator");

                    b.HasIndex("ObservatorId");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("TransferStatusTypeId");

                    b.HasIndex("StartTime");

                    b.ToTable("Session");

                    b.HasDiscriminator().HasValue("Session");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HyFive.Domain.Place.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentTypeId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("Name");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("HyFive.Domain.Place.DepartmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("DepartmentType");
                });

            modelBuilder.Entity("HyFive.Domain.Place.HealthOrganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("RegionalHealthOrganizationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegionalHealthOrganizationId");

                    b.ToTable("HealthOrganization");
                });

            modelBuilder.Entity("HyFive.Domain.Place.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("HERId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("HealthOrganizationId")
                        .HasColumnType("integer");

                    b.Property<int?>("InstitutionTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("MunicipalityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation");

                    b.HasIndex("HERId");

                    b.HasIndex("HealthOrganizationId");

                    b.HasIndex("InstitutionTypeId");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("Name");

                    b.HasIndex("RegionId");

                    b.ToTable("Institution");
                });

            modelBuilder.Entity("HyFive.Domain.Place.InstitutionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("InstitutionType");
                });

            modelBuilder.Entity("HyFive.Domain.Place.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("Name");

                    b.ToTable("Clinic");
                });

            modelBuilder.Entity("HyFive.Domain.Place.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Number")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("Id");

                    b.ToTable("Municipality");
                });

            modelBuilder.Entity("HyFive.Domain.Place.PredefinedComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SessionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.ToTable("PredefinedComment");
                });

            modelBuilder.Entity("HyFive.Domain.Place.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("HyFive.Domain.Place.RegionalHealthOrganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("RegionalHealthOrganization");
                });

            modelBuilder.Entity("HyFive.Domain.User.FhiAdmin", b =>
                {
                    b.HasBaseType("HyFive.Domain.User.User");

                    b.HasDiscriminator().HasValue("FhiAdmin");
                });

            modelBuilder.Entity("HyFive.Domain.User.Coordinator", b =>
                {
                    b.HasBaseType("HyFive.Domain.User.User");

                    b.HasDiscriminator().HasValue("Coordinator");
                });

            modelBuilder.Entity("HyFive.Domain.User.Observer", b =>
                {
                    b.HasBaseType("HyFive.Domain.User.User");

                    b.HasDiscriminator().HasValue("Observer");
                });

            modelBuilder.Entity("HyFive.Domain.Session.ProtectiveEquipmentSession", b =>
                {
                    b.HasBaseType("HyFive.Domain.Session.Session");

                    b.HasDiscriminator().HasValue("ProtectiveEquipmentSession");
                });

            modelBuilder.Entity("HyFive.Domain.Session.FourIndicationsSession", b =>
                {
                    b.HasBaseType("HyFive.Domain.Session.Session");

                    b.HasDiscriminator().HasValue("FourIndicationsSession");
                });

            modelBuilder.Entity("HyFive.Domain.Session.HandJewelrySession", b =>
                {
                    b.HasBaseType("HyFive.Domain.Session.Session");

                    b.HasDiscriminator().HasValue("HandJewelrySession");
                });

            modelBuilder.Entity("HyFive.Domain.Session.GloveSession", b =>
                {
                    b.HasBaseType("HyFive.Domain.Session.Session");

                    b.HasDiscriminator().HasValue("GloveSession");
                });

            modelBuilder.Entity("DepartmentClinic", b =>
                {
                    b.HasOne("HyFive.Domain.Place.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Place.Clinic", null)
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DepartmentRole", b =>
                {
                    b.HasOne("HyFive.Domain.Place.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProtectiveEquipmentMisuseType", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipment", null)
                        .WithMany()
                        .HasForeignKey("ProtectiveEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.MisuseType", null)
                        .WithMany()
                        .HasForeignKey("MisuseTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FourIndicationsObservationIndicationType", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.IndicationType", null)
                        .WithMany()
                        .HasForeignKey("IndicationTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.FourIndicationsObservation", null)
                        .WithMany()
                        .HasForeignKey("ObservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HandJewelryObservationHandJewelryType", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.HandJewelryType", null)
                        .WithMany()
                        .HasForeignKey("HandJewelryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.HandJewelryObservation", null)
                        .WithMany()
                        .HasForeignKey("ObservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GloveWithIndicationTypeGloveObservation", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.Gloves.GloveWithIndicationType", null)
                        .WithMany()
                        .HasForeignKey("GloveWithIndicationTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.Gloves.GloveObservation", null)
                        .WithMany()
                        .HasForeignKey("ObservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GloveObservationWithoutIndicationType", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.Gloves.GloveWithoutIndicationType", null)
                        .WithMany()
                        .HasForeignKey("GloveWithoutIndicationTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.Gloves.GloveObservation", null)
                        .WithMany()
                        .HasForeignKey("ObservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyFive.Domain.User.User", b =>
                {
                    b.HasOne("HyFive.Domain.Place.Institution", "Institution")
                        .WithMany("Users")
                        .HasForeignKey("InstitutionId");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Activity", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.ActivityType", "ActivityType")
                        .WithMany()
                        .HasForeignKey("ActivityTypeId");

                    b.Navigation("ActivityType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipment", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentObservation", "ProtectiveEquipmentObservation")
                        .WithMany("ProtectiveEquipmentList")
                        .HasForeignKey("ProtectiveEquipmentObservationId");

                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentType", "Utstyrstype")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId");

                    b.Navigation("ProtectiveEquipmentObservation");

                    b.Navigation("Utstyrstype");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentObservation", b =>
                {
                    b.HasOne("HyFive.Domain.Session.ProtectiveEquipmentSession", "ProtectiveEquipmentSession")
                        .WithMany("Observations")
                        .HasForeignKey("ProtectiveEquipmentSessionId");

                    b.HasOne("HyFive.Domain.Observation.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentSettingType", "Settingtype")
                        .WithMany()
                        .HasForeignKey("SettingTypeId");

                    b.Navigation("ProtectiveEquipmentSession");

                    b.Navigation("Role");

                    b.Navigation("Settingtype");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentSettingTypeProtectiveEquipmentType", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentType", "ProtectiveEquipmentType")
                        .WithMany("ProtectiveEquipmentSettingTypeProtectiveEquipmentTypes")
                        .HasForeignKey("ProtectiveEquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentSettingType", "ProtectiveEquipmentSettingType")
                        .WithMany("ProtectiveEquipmentSettingTypeProtectiveEquipmentTypes")
                        .HasForeignKey("ProtectiveEquipmentSettingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProtectiveEquipmentSettingTypeProtectiveEquipmentType_Beskyt~1");

                    b.Navigation("ProtectiveEquipmentType");

                    b.Navigation("ProtectiveEquipmentSettingType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.MisuseType", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentType", "ProtectiveEquipmentType")
                        .WithMany("MisuseTypes")
                        .HasForeignKey("ProtectiveEquipmentTypeId");

                    b.Navigation("ProtectiveEquipmentType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.FourIndicationsObservation", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId");

                    b.HasOne("HyFive.Domain.Session.FourIndicationsSession", "FourIndicationsSession")
                        .WithMany("Observations")
                        .HasForeignKey("FourIndicationsSessionId");

                    b.HasOne("HyFive.Domain.Observation.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Activity");

                    b.Navigation("FourIndicationsSession");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.HandJewelryObservation", b =>
                {
                    b.HasOne("HyFive.Domain.Session.HandJewelrySession", "HandJewelrySession")
                        .WithMany("Observations")
                        .HasForeignKey("HandJewelrySessionId");

                    b.HasOne("HyFive.Domain.Observation.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("HandJewelrySession");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Gloves.GloveObservation", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.Gloves.HandHygieneAfterGloveUseType", "HandHygieneAfterGloveUseType")
                        .WithMany()
                        .HasForeignKey("HandHygieneAfterGloveUseTypeId");

                    b.HasOne("HyFive.Domain.Session.GloveSession", "GloveSession")
                        .WithMany("Observations")
                        .HasForeignKey("GloveSessionId");

                    b.HasOne("HyFive.Domain.Observation.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("HandHygieneAfterGloveUseType");

                    b.Navigation("GloveSession");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HyFive.Domain.Session.Session", b =>
                {
                    b.HasOne("HyFive.Domain.Place.Department", "Department")
                        .WithMany("Sessions")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("HyFive.Domain.User.Observer", "Observer")
                        .WithMany()
                        .HasForeignKey("ObservatorId");

                    b.HasOne("HyFive.Domain.Session.TransferStatusType", "TransferStatus")
                        .WithMany("Sessions")
                        .HasForeignKey("TransferStatusTypeId");

                    b.Navigation("Department");

                    b.Navigation("Observer");

                    b.Navigation("TransferStatus");
                });

            modelBuilder.Entity("HyFive.Domain.Place.Department", b =>
                {
                    b.HasOne("HyFive.Domain.Place.DepartmentType", "DepartmentType")
                        .WithMany()
                        .HasForeignKey("DepartmentTypeId");

                    b.HasOne("HyFive.Domain.Place.Institution", "Institution")
                        .WithMany("Departments")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentType");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("HyFive.Domain.Place.HealthOrganization", b =>
                {
                    b.HasOne("HyFive.Domain.Place.RegionalHealthOrganization", "RegionalHealthOrganization")
                        .WithMany()
                        .HasForeignKey("RegionalHealthOrganizationId");

                    b.Navigation("RegionalHealthOrganization");
                });

            modelBuilder.Entity("HyFive.Domain.Place.Institution", b =>
                {
                    b.HasOne("HyFive.Domain.Place.HealthOrganization", "HealthOrganization")
                        .WithMany()
                        .HasForeignKey("HealthOrganizationId");

                    b.HasOne("HyFive.Domain.Place.InstitutionType", "InstitutionType")
                        .WithMany()
                        .HasForeignKey("InstitutionTypeId");

                    b.HasOne("HyFive.Domain.Place.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId");

                    b.HasOne("HyFive.Domain.Place.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.Navigation("HealthOrganization");

                    b.Navigation("InstitutionType");

                    b.Navigation("Municipality");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("HyFive.Domain.Place.Clinic", b =>
                {
                    b.HasOne("HyFive.Domain.Place.Institution", "Institution")
                        .WithMany("Clinics")
                        .HasForeignKey("InstitutionId");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("HyFive.Domain.Place.PredefinedComment", b =>
                {
                    b.HasOne("HyFive.Domain.Place.Institution", null)
                        .WithMany("PredefinedComments")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentObservation", b =>
                {
                    b.Navigation("ProtectiveEquipmentList");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentType", b =>
                {
                    b.Navigation("ProtectiveEquipmentSettingTypeProtectiveEquipmentTypes");

                    b.Navigation("MisuseTypes");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentSettingType", b =>
                {
                    b.Navigation("ProtectiveEquipmentSettingTypeProtectiveEquipmentTypes");
                });

            modelBuilder.Entity("HyFive.Domain.Session.TransferStatusType", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("HyFive.Domain.Place.Department", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("HyFive.Domain.Place.Institution", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Users");

                    b.Navigation("Clinics");

                    b.Navigation("PredefinedComments");
                });

            modelBuilder.Entity("HyFive.Domain.Session.ProtectiveEquipmentSession", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("HyFive.Domain.Session.FourIndicationsSession", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("HyFive.Domain.Session.HandJewelrySession", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("HyFive.Domain.Session.GloveSession", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
