// <auto-generated />
using System;
using HyFive.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HyFive.DataAccess.Migrations
{
    [DbContext(typeof(HandHygieneContext))]
    [Migration("20250410142557_InitialMigrationSQL")]
    partial class InitialMigrationSQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AvdelingKlinikk", b =>
                {
                    b.Property<int>("AvdelingerId")
                        .HasColumnType("integer");

                    b.Property<int>("KlinikkerId")
                        .HasColumnType("integer");

                    b.HasKey("AvdelingerId", "KlinikkerId");

                    b.HasIndex("KlinikkerId");

                    b.ToTable("AvdelingKlinikk");
                });

            modelBuilder.Entity("AvdelingRolle", b =>
                {
                    b.Property<int>("AvdelingerId")
                        .HasColumnType("integer");

                    b.Property<int>("RollerId")
                        .HasColumnType("integer");

                    b.HasKey("AvdelingerId", "RollerId");

                    b.HasIndex("RollerId");

                    b.ToTable("AvdelingRolle");
                });

            modelBuilder.Entity("BeskyttelsesutstyrFeilbrukType", b =>
                {
                    b.Property<int>("BeskyttelsesutstyrId")
                        .HasColumnType("integer");

                    b.Property<int>("FeilbruktyperId")
                        .HasColumnType("integer");

                    b.HasKey("BeskyttelsesutstyrId", "FeilbruktyperId");

                    b.HasIndex("FeilbruktyperId");

                    b.ToTable("BeskyttelsesutstyrFeilbrukType");
                });

            modelBuilder.Entity("FireIndikasjonerObservasjonIndikasjonType", b =>
                {
                    b.Property<int>("IndikasjonstyperId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservasjonerId")
                        .HasColumnType("uuid");

                    b.HasKey("IndikasjonstyperId", "ObservasjonerId");

                    b.HasIndex("ObservasjonerId");

                    b.ToTable("FireIndikasjonerObservasjonIndikasjonType");
                });

            modelBuilder.Entity("HandsmykkeObservasjonHandsmykkeType", b =>
                {
                    b.Property<int>("HandsmykkerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservasjonerId")
                        .HasColumnType("uuid");

                    b.HasKey("HandsmykkerId", "ObservasjonerId");

                    b.HasIndex("ObservasjonerId");

                    b.ToTable("HandsmykkeObservasjonHandsmykkeType");
                });

            modelBuilder.Entity("HanskeMedIndikasjonTypeHanskeObservasjon", b =>
                {
                    b.Property<int>("HanskeMedIndikasjonTyperId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservasjonerId")
                        .HasColumnType("uuid");

                    b.HasKey("HanskeMedIndikasjonTyperId", "ObservasjonerId");

                    b.HasIndex("ObservasjonerId");

                    b.ToTable("HanskeMedIndikasjonTypeHanskeObservasjon");
                });

            modelBuilder.Entity("HanskeObservasjonHanskeUtenIndikasjonType", b =>
                {
                    b.Property<int>("HanskeUtenIndikasjonTyperId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservasjonerId")
                        .HasColumnType("uuid");

                    b.HasKey("HanskeUtenIndikasjonTyperId", "ObservasjonerId");

                    b.HasIndex("ObservasjonerId");

                    b.ToTable("HanskeObservasjonHanskeUtenIndikasjonType");
                });

            modelBuilder.Entity("HyFive.Domene.Bruker.Bruker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Epost")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("ErDeaktivert")
                        .HasColumnType("boolean");

                    b.Property<string>("Etternavn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HPRNummer")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IdentityPseudonym")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Opprettettidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HPRNummer");

                    b.HasIndex("IdentityPseudonym");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Bruker");

                    b.HasDiscriminator().HasValue("Bruker");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HyFive.Domene.Bruker.ForesporselOmBrukertilgang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BehandletAvBrukerId")
                        .HasColumnType("integer");

                    b.Property<string>("BehandletAvBrukernavn")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BehandletTidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BrukerEtternavn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BrukerFornavn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HPRNummer")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IdentityPseudonym")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Opprettettidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("ForesporselOmBrukertilgang");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Aktivitet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AktivitetTypeId")
                        .HasColumnType("integer");

                    b.Property<bool?>("BenyttetHanske")
                        .HasColumnType("boolean");

                    b.Property<int>("SekunderBrukt")
                        .HasColumnType("integer");

                    b.Property<bool>("TidtakingBleUtfort")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AktivitetTypeId");

                    b.ToTable("Aktivitet");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.AktivitetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("AktivitetType");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Beskyttelsesutstyr.Beskyttelsesutstyr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("BeskyttelsesutstyrObservasjonId")
                        .HasColumnType("uuid");

                    b.Property<bool>("BleBenyttet")
                        .HasColumnType("boolean");

                    b.Property<bool>("BleBenyttetRiktig")
                        .HasColumnType("boolean");

                    b.Property<bool>("ErIndikert")
                        .HasColumnType("boolean");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("UtstyrstypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BeskyttelsesutstyrObservasjonId");

                    b.HasIndex("UtstyrstypeId");

                    b.ToTable("Beskyttelsesutstyr");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrObservasjon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BeskyttelsesutstyrSesjonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kommentar")
                        .HasColumnType("text");

                    b.Property<DateTime>("Opprettettidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RolleId")
                        .HasColumnType("integer");

                    b.Property<int?>("SettingtypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BeskyttelsesutstyrSesjonId");

                    b.HasIndex("Opprettettidspunkt");

                    b.HasIndex("RegistrationTime");

                    b.HasIndex("RolleId");

                    b.HasIndex("SettingtypeId");

                    b.ToTable("BeskyttelsesutstyrObservasjon");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("BeskyttelsesutstyrType");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrsettingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("BeskyttelsesutstyrsettingType");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrsettingTypeBeskyttelsesutstyrType", b =>
                {
                    b.Property<int>("BeskyttelsesutstyrTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("BeskyttelsesutstyrsettingTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("ErDefaultIndikert")
                        .HasColumnType("boolean");

                    b.HasKey("BeskyttelsesutstyrTypeId", "BeskyttelsesutstyrsettingTypeId");

                    b.HasIndex("BeskyttelsesutstyrsettingTypeId");

                    b.ToTable("BeskyttelsesutstyrsettingTypeBeskyttelsesutstyrType");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Beskyttelsesutstyr.FeilbrukType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BeskyttelsesutstyrTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BeskyttelsesutstyrTypeId");

                    b.HasIndex("Name");

                    b.ToTable("FeilbrukType");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.FireIndikasjonerObservasjon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AktivitetId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FireIndikasjonerSesjonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("Opprettettidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RolleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AktivitetId");

                    b.HasIndex("FireIndikasjonerSesjonId");

                    b.HasIndex("Opprettettidspunkt");

                    b.HasIndex("RegistrationTime");

                    b.HasIndex("RolleId");

                    b.ToTable("FireIndikasjonerObservasjon");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.HandsmykkeObservasjon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HandsmykkeSesjonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kommentar")
                        .HasColumnType("text");

                    b.Property<DateTime>("Opprettettidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RolleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HandsmykkeSesjonId");

                    b.HasIndex("Opprettettidspunkt");

                    b.HasIndex("RegistrationTime");

                    b.HasIndex("RolleId");

                    b.ToTable("HandsmykkeObservasjon");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.HandsmykkeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ErAktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Rekkefolge")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("HandsmykkeType");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Hansker.HandhygieneEtterHanskebrukType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("HandhygieneEtterHanskebrukType");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Hansker.HanskeMedIndikasjonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("HanskeMedIndikasjonType");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Hansker.HanskeObservasjon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BenyttetHanske")
                        .HasColumnType("boolean");

                    b.Property<int?>("HandhygieneEtterHanskebrukTypeId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("HanskeSesjonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kommentar")
                        .HasColumnType("text");

                    b.Property<DateTime>("Opprettettidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RolleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HandhygieneEtterHanskebrukTypeId");

                    b.HasIndex("HanskeSesjonId");

                    b.HasIndex("Opprettettidspunkt");

                    b.HasIndex("RegistrationTime");

                    b.HasIndex("RolleId");

                    b.ToTable("HanskeObservasjon");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Hansker.HanskeUtenIndikasjonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("HanskeUtenIndikasjonType");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.IndikasjonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nummer")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("IndikasjonType");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Beskrivelse")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("HyFive.Domene.Sesjon.OverforingstatusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("OverforingstatusType");
                });

            modelBuilder.Entity("HyFive.Domene.Sesjon.Sesjon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("ObservatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Opprettettidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OverforingstatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Starttidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Discriminator");

                    b.HasIndex("ObservatorId");

                    b.HasIndex("Opprettettidspunkt");

                    b.HasIndex("OverforingstatusId");

                    b.HasIndex("Starttidspunkt");

                    b.ToTable("Sesjon");

                    b.HasDiscriminator().HasValue("Sesjon");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HyFive.Domene.Sted.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvdelingtypeId")
                        .HasColumnType("integer");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("AvdelingtypeId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("Name");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("HyFive.Domene.Sted.AvdelingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("AvdelingType");
                });

            modelBuilder.Entity("HyFive.Domene.Sted.Helseforetak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("RegionaltHelseforetakId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegionaltHelseforetakId");

                    b.ToTable("Helseforetak");
                });

            modelBuilder.Entity("HyFive.Domene.Sted.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Forkortelse")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("HERId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("HelseforetakId")
                        .HasColumnType("integer");

                    b.Property<int?>("InstitusjontypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("KommuneId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("Opprettettidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Forkortelse");

                    b.HasIndex("HERId");

                    b.HasIndex("HelseforetakId");

                    b.HasIndex("InstitusjontypeId");

                    b.HasIndex("KommuneId");

                    b.HasIndex("Name");

                    b.HasIndex("RegionId");

                    b.ToTable("Institution");
                });

            modelBuilder.Entity("HyFive.Domene.Sted.InstitusjonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("InstitusjonType");
                });

            modelBuilder.Entity("HyFive.Domene.Sted.Klinikk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("Name");

                    b.ToTable("Klinikk");
                });

            modelBuilder.Entity("HyFive.Domene.Sted.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nummer")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("Id");

                    b.ToTable("Municipality");
                });

            modelBuilder.Entity("HyFive.Domene.Sted.PredefinertKommentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SessionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.ToTable("PredefinertKommentar");
                });

            modelBuilder.Entity("HyFive.Domene.Sted.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("HyFive.Domene.Sted.RegionaltHelseforetak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("RegionaltHelseforetak");
                });

            modelBuilder.Entity("HyFive.Domene.Bruker.FhiAdmin", b =>
                {
                    b.HasBaseType("HyFive.Domene.Bruker.Bruker");

                    b.HasDiscriminator().HasValue("FhiAdmin");
                });

            modelBuilder.Entity("HyFive.Domene.Bruker.Coordinator", b =>
                {
                    b.HasBaseType("HyFive.Domene.Bruker.Bruker");

                    b.HasDiscriminator().HasValue("Coordinator");
                });

            modelBuilder.Entity("HyFive.Domene.Bruker.Observer", b =>
                {
                    b.HasBaseType("HyFive.Domene.Bruker.Bruker");

                    b.HasDiscriminator().HasValue("Observer");
                });

            modelBuilder.Entity("HyFive.Domene.Sesjon.BeskyttelsesutstyrSesjon", b =>
                {
                    b.HasBaseType("HyFive.Domene.Sesjon.Sesjon");

                    b.HasDiscriminator().HasValue("BeskyttelsesutstyrSesjon");
                });

            modelBuilder.Entity("HyFive.Domene.Sesjon.FireIndikasjonerSesjon", b =>
                {
                    b.HasBaseType("HyFive.Domene.Sesjon.Sesjon");

                    b.HasDiscriminator().HasValue("FireIndikasjonerSesjon");
                });

            modelBuilder.Entity("HyFive.Domene.Sesjon.HandsmykkeSesjon", b =>
                {
                    b.HasBaseType("HyFive.Domene.Sesjon.Sesjon");

                    b.HasDiscriminator().HasValue("HandsmykkeSesjon");
                });

            modelBuilder.Entity("HyFive.Domene.Sesjon.GloveSession", b =>
                {
                    b.HasBaseType("HyFive.Domene.Sesjon.Sesjon");

                    b.HasDiscriminator().HasValue("GloveSession");
                });

            modelBuilder.Entity("AvdelingKlinikk", b =>
                {
                    b.HasOne("HyFive.Domene.Sted.Department", null)
                        .WithMany()
                        .HasForeignKey("AvdelingerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domene.Sted.Klinikk", null)
                        .WithMany()
                        .HasForeignKey("KlinikkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AvdelingRolle", b =>
                {
                    b.HasOne("HyFive.Domene.Sted.Department", null)
                        .WithMany()
                        .HasForeignKey("AvdelingerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domene.Observasjon.Role", null)
                        .WithMany()
                        .HasForeignKey("RollerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeskyttelsesutstyrFeilbrukType", b =>
                {
                    b.HasOne("HyFive.Domene.Observasjon.Beskyttelsesutstyr.Beskyttelsesutstyr", null)
                        .WithMany()
                        .HasForeignKey("BeskyttelsesutstyrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domene.Observasjon.Beskyttelsesutstyr.FeilbrukType", null)
                        .WithMany()
                        .HasForeignKey("FeilbruktyperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FireIndikasjonerObservasjonIndikasjonType", b =>
                {
                    b.HasOne("HyFive.Domene.Observasjon.IndikasjonType", null)
                        .WithMany()
                        .HasForeignKey("IndikasjonstyperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domene.Observasjon.FireIndikasjonerObservasjon", null)
                        .WithMany()
                        .HasForeignKey("ObservasjonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HandsmykkeObservasjonHandsmykkeType", b =>
                {
                    b.HasOne("HyFive.Domene.Observasjon.HandsmykkeType", null)
                        .WithMany()
                        .HasForeignKey("HandsmykkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domene.Observasjon.HandsmykkeObservasjon", null)
                        .WithMany()
                        .HasForeignKey("ObservasjonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HanskeMedIndikasjonTypeHanskeObservasjon", b =>
                {
                    b.HasOne("HyFive.Domene.Observasjon.Hansker.HanskeMedIndikasjonType", null)
                        .WithMany()
                        .HasForeignKey("HanskeMedIndikasjonTyperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domene.Observasjon.Hansker.HanskeObservasjon", null)
                        .WithMany()
                        .HasForeignKey("ObservasjonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HanskeObservasjonHanskeUtenIndikasjonType", b =>
                {
                    b.HasOne("HyFive.Domene.Observasjon.Hansker.HanskeUtenIndikasjonType", null)
                        .WithMany()
                        .HasForeignKey("HanskeUtenIndikasjonTyperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domene.Observasjon.Hansker.HanskeObservasjon", null)
                        .WithMany()
                        .HasForeignKey("ObservasjonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyFive.Domene.Bruker.Bruker", b =>
                {
                    b.HasOne("HyFive.Domene.Sted.Institution", "Institution")
                        .WithMany("Brukere")
                        .HasForeignKey("InstitutionId");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Aktivitet", b =>
                {
                    b.HasOne("HyFive.Domene.Observasjon.AktivitetType", "AktivitetType")
                        .WithMany()
                        .HasForeignKey("AktivitetTypeId");

                    b.Navigation("AktivitetType");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Beskyttelsesutstyr.Beskyttelsesutstyr", b =>
                {
                    b.HasOne("HyFive.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrObservasjon", "BeskyttelsesutstyrObservasjon")
                        .WithMany("Beskyttelsesutstyrliste")
                        .HasForeignKey("BeskyttelsesutstyrObservasjonId");

                    b.HasOne("HyFive.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrType", "Utstyrstype")
                        .WithMany()
                        .HasForeignKey("UtstyrstypeId");

                    b.Navigation("BeskyttelsesutstyrObservasjon");

                    b.Navigation("Utstyrstype");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrObservasjon", b =>
                {
                    b.HasOne("HyFive.Domene.Sesjon.BeskyttelsesutstyrSesjon", "BeskyttelsesutstyrSesjon")
                        .WithMany("Observasjoner")
                        .HasForeignKey("BeskyttelsesutstyrSesjonId");

                    b.HasOne("HyFive.Domene.Observasjon.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RolleId");

                    b.HasOne("HyFive.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrsettingType", "Settingtype")
                        .WithMany()
                        .HasForeignKey("SettingtypeId");

                    b.Navigation("BeskyttelsesutstyrSesjon");

                    b.Navigation("Role");

                    b.Navigation("Settingtype");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrsettingTypeBeskyttelsesutstyrType", b =>
                {
                    b.HasOne("HyFive.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrType", "BeskyttelsesutstyrType")
                        .WithMany("BeskyttelsesutstyrsettingTypeBeskyttelsesutstyrTyper")
                        .HasForeignKey("BeskyttelsesutstyrTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrsettingType", "BeskyttelsesutstyrsettingType")
                        .WithMany("BeskyttelsesutstyrsettingTypeBeskyttelsesutstyrTyper")
                        .HasForeignKey("BeskyttelsesutstyrsettingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BeskyttelsesutstyrsettingTypeBeskyttelsesutstyrType_Beskyt~1");

                    b.Navigation("BeskyttelsesutstyrType");

                    b.Navigation("BeskyttelsesutstyrsettingType");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Beskyttelsesutstyr.FeilbrukType", b =>
                {
                    b.HasOne("HyFive.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrType", "BeskyttelsesutstyrType")
                        .WithMany("Feilbruktyper")
                        .HasForeignKey("BeskyttelsesutstyrTypeId");

                    b.Navigation("BeskyttelsesutstyrType");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.FireIndikasjonerObservasjon", b =>
                {
                    b.HasOne("HyFive.Domene.Observasjon.Aktivitet", "Aktivitet")
                        .WithMany()
                        .HasForeignKey("AktivitetId");

                    b.HasOne("HyFive.Domene.Sesjon.FireIndikasjonerSesjon", "FireIndikasjonerSesjon")
                        .WithMany("Observasjoner")
                        .HasForeignKey("FireIndikasjonerSesjonId");

                    b.HasOne("HyFive.Domene.Observasjon.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RolleId");

                    b.Navigation("Aktivitet");

                    b.Navigation("FireIndikasjonerSesjon");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.HandsmykkeObservasjon", b =>
                {
                    b.HasOne("HyFive.Domene.Sesjon.HandsmykkeSesjon", "HandsmykkeSesjon")
                        .WithMany("Observasjoner")
                        .HasForeignKey("HandsmykkeSesjonId");

                    b.HasOne("HyFive.Domene.Observasjon.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RolleId");

                    b.Navigation("HandsmykkeSesjon");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Hansker.HanskeObservasjon", b =>
                {
                    b.HasOne("HyFive.Domene.Observasjon.Hansker.HandhygieneEtterHanskebrukType", "HandhygieneEtterHanskebrukType")
                        .WithMany()
                        .HasForeignKey("HandhygieneEtterHanskebrukTypeId");

                    b.HasOne("HyFive.Domene.Sesjon.GloveSession", "GloveSession")
                        .WithMany("Observasjoner")
                        .HasForeignKey("HanskeSesjonId");

                    b.HasOne("HyFive.Domene.Observasjon.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RolleId");

                    b.Navigation("HandhygieneEtterHanskebrukType");

                    b.Navigation("GloveSession");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HyFive.Domene.Sesjon.Sesjon", b =>
                {
                    b.HasOne("HyFive.Domene.Sted.Department", "Department")
                        .WithMany("Sesjoner")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("HyFive.Domene.Bruker.Observer", "Observer")
                        .WithMany()
                        .HasForeignKey("ObservatorId");

                    b.HasOne("HyFive.Domene.Sesjon.OverforingstatusType", "TransmissionStatus")
                        .WithMany("Sesjoner")
                        .HasForeignKey("OverforingstatusId");

                    b.Navigation("Department");

                    b.Navigation("Observer");

                    b.Navigation("TransmissionStatus");
                });

            modelBuilder.Entity("HyFive.Domene.Sted.Department", b =>
                {
                    b.HasOne("HyFive.Domene.Sted.AvdelingType", "DepartmentType")
                        .WithMany()
                        .HasForeignKey("AvdelingtypeId");

                    b.HasOne("HyFive.Domene.Sted.Institution", "Institution")
                        .WithMany("Avdelinger")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentType");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("HyFive.Domene.Sted.Helseforetak", b =>
                {
                    b.HasOne("HyFive.Domene.Sted.RegionaltHelseforetak", "RegionaltHelseforetak")
                        .WithMany()
                        .HasForeignKey("RegionaltHelseforetakId");

                    b.Navigation("RegionaltHelseforetak");
                });

            modelBuilder.Entity("HyFive.Domene.Sted.Institution", b =>
                {
                    b.HasOne("HyFive.Domene.Sted.Helseforetak", "Helseforetak")
                        .WithMany()
                        .HasForeignKey("HelseforetakId");

                    b.HasOne("HyFive.Domene.Sted.InstitusjonType", "Institusjontype")
                        .WithMany()
                        .HasForeignKey("InstitusjontypeId");

                    b.HasOne("HyFive.Domene.Sted.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("KommuneId");

                    b.HasOne("HyFive.Domene.Sted.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.Navigation("Helseforetak");

                    b.Navigation("Institusjontype");

                    b.Navigation("Municipality");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("HyFive.Domene.Sted.Klinikk", b =>
                {
                    b.HasOne("HyFive.Domene.Sted.Institution", "Institution")
                        .WithMany("Klinikker")
                        .HasForeignKey("InstitutionId");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("HyFive.Domene.Sted.PredefinertKommentar", b =>
                {
                    b.HasOne("HyFive.Domene.Sted.Institution", null)
                        .WithMany("PredefinerteKommmentarer")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrObservasjon", b =>
                {
                    b.Navigation("Beskyttelsesutstyrliste");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrType", b =>
                {
                    b.Navigation("BeskyttelsesutstyrsettingTypeBeskyttelsesutstyrTyper");

                    b.Navigation("Feilbruktyper");
                });

            modelBuilder.Entity("HyFive.Domene.Observasjon.Beskyttelsesutstyr.BeskyttelsesutstyrsettingType", b =>
                {
                    b.Navigation("BeskyttelsesutstyrsettingTypeBeskyttelsesutstyrTyper");
                });

            modelBuilder.Entity("HyFive.Domene.Sesjon.OverforingstatusType", b =>
                {
                    b.Navigation("Sesjoner");
                });

            modelBuilder.Entity("HyFive.Domene.Sted.Department", b =>
                {
                    b.Navigation("Sesjoner");
                });

            modelBuilder.Entity("HyFive.Domene.Sted.Institution", b =>
                {
                    b.Navigation("Avdelinger");

                    b.Navigation("Brukere");

                    b.Navigation("Klinikker");

                    b.Navigation("PredefinerteKommmentarer");
                });

            modelBuilder.Entity("HyFive.Domene.Sesjon.BeskyttelsesutstyrSesjon", b =>
                {
                    b.Navigation("Observasjoner");
                });

            modelBuilder.Entity("HyFive.Domene.Sesjon.FireIndikasjonerSesjon", b =>
                {
                    b.Navigation("Observasjoner");
                });

            modelBuilder.Entity("HyFive.Domene.Sesjon.HandsmykkeSesjon", b =>
                {
                    b.Navigation("Observasjoner");
                });

            modelBuilder.Entity("HyFive.Domene.Sesjon.GloveSession", b =>
                {
                    b.Navigation("Observasjoner");
                });
#pragma warning restore 612, 618
        }
    }
}
