// <auto-generated />
using System;
using HyFive.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HyFive.DataAccess.Migrations
{
    [DbContext(typeof(HandHygieneContext))]
    [Migration("20260505100743_addCityTable")]
    partial class addCityTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FiveIndicationsObservationIndicationTypes", b =>
                {
                    b.Property<int>("IndicationTypesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservationsId")
                        .HasColumnType("uuid");

                    b.HasKey("IndicationTypesId", "ObservationsId");

                    b.HasIndex("ObservationsId");

                    b.ToTable("FiveIndicationsObservationIndicationTypes");
                });

            modelBuilder.Entity("GloveObservationGloveWithIndicationType", b =>
                {
                    b.Property<int>("GloveWithIndicationTypesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservationsId")
                        .HasColumnType("uuid");

                    b.HasKey("GloveWithIndicationTypesId", "ObservationsId");

                    b.HasIndex("ObservationsId");

                    b.ToTable("GloveObservationGloveWithIndicationType");
                });

            modelBuilder.Entity("GloveObservationGloveWithoutIndicationType", b =>
                {
                    b.Property<int>("GloveWithoutIndicationTypesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservationsId")
                        .HasColumnType("uuid");

                    b.HasKey("GloveWithoutIndicationTypesId", "ObservationsId");

                    b.HasIndex("ObservationsId");

                    b.ToTable("GloveObservationGloveWithoutIndicationType");
                });

            modelBuilder.Entity("HandJewelryObservationHandJewelryType", b =>
                {
                    b.Property<int>("HandJewelriesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservationsId")
                        .HasColumnType("uuid");

                    b.HasKey("HandJewelriesId", "ObservationsId");

                    b.HasIndex("ObservationsId");

                    b.ToTable("HandJewelryObservationHandJewelryType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityTypeId")
                        .HasColumnType("integer");

                    b.Property<bool?>("GlovesUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("SecondsUsed")
                        .HasColumnType("integer");

                    b.Property<bool>("TimingWasPerformed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("ActivityType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.FiveIndicationsObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FiveIndicationsSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegisteredTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("FiveIndicationsSessionId");

                    b.HasIndex("RegisteredTime");

                    b.HasIndex("RoleId");

                    b.ToTable("FiveIndicationsObservation");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Gloves.GloveObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GloveSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("GlovesUsed")
                        .HasColumnType("boolean");

                    b.Property<int?>("PostGloveHandHygieneTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegisteredTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("GloveSessionId");

                    b.HasIndex("PostGloveHandHygieneTypeId");

                    b.HasIndex("RegisteredTime");

                    b.HasIndex("RoleId");

                    b.ToTable("GloveObservation");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Gloves.GloveWithIndicationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("GloveWithIndicationType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Gloves.GloveWithoutIndicationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("GloveWithoutIndicationType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Gloves.HandHygieneAfterGloveUseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("HandHygieneAfterGloveUseType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.HandJewelryObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HandJewelrySessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegisteredTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("HandJewelrySessionId");

                    b.HasIndex("RegisteredTime");

                    b.HasIndex("RoleId");

                    b.ToTable("HandJewelryObservation");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.HandJewelryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("HandJewelryType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.IndicationTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Number")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("IndicationType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.OrganisationUnitRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrganisationUnitId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("OrganisationUnitId", "RoleId")
                        .IsUnique();

                    b.ToTable("OrganisationUnitRole");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.MisuseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ProtectiveEquipmentTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ProtectiveEquipmentTypeId");

                    b.ToTable("MisuseType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("EquipmentTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProtectiveEquipmentObservationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasUsed")
                        .HasColumnType("boolean");

                    b.Property<bool>("WasUsedCorrectly")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("ProtectiveEquipmentObservationId");

                    b.ToTable("ProtectiveEquipment");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProtectiveEquipmentSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegisteredTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int?>("SettingTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("ProtectiveEquipmentSessionId");

                    b.HasIndex("RegisteredTime");

                    b.HasIndex("RoleId");

                    b.HasIndex("SettingTypeId");

                    b.ToTable("ProtectiveEquipmentObservation");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentSettingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("ProtectiveEquipmentSettingType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentSettingTypeProtectiveEquipmentType", b =>
                {
                    b.Property<int>("ProtectiveEquipmentTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ProtectiveEquipmentSettingTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.HasKey("ProtectiveEquipmentTypeId", "ProtectiveEquipmentSettingTypeId");

                    b.HasIndex("ProtectiveEquipmentSettingTypeId");

                    b.ToTable("ProtectiveEquipmentSettingTypeProtectiveEquipmentType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("ProtectiveEquipmentType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("HyFive.Domain.Place.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Street")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("HyFive.Domain.Place.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("HyFive.Domain.Place.OrganisationUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("AddressId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("LevelId");

                    b.HasIndex("TypeId");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique();

                    b.ToTable("OrganisationUnit");
                });

            modelBuilder.Entity("HyFive.Domain.Place.OrganisationUnitAssociation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociationType")
                        .HasColumnType("integer");

                    b.Property<int>("SourceOrganisationUnitId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetOrganisationUnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TargetOrganisationUnitId");

                    b.HasIndex("SourceOrganisationUnitId", "TargetOrganisationUnitId", "AssociationType")
                        .IsUnique();

                    b.ToTable("OrganisationUnitAssociation", (string)null);
                });

            modelBuilder.Entity("HyFive.Domain.Place.OrganisationUnitLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("OrganisationUnitLevel");
                });

            modelBuilder.Entity("HyFive.Domain.Place.OrganisationUnitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("OrganisationUnitType");
                });

            modelBuilder.Entity("HyFive.Domain.Place.PredefinedComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("OrganisationUnitId")
                        .HasColumnType("integer");

                    b.Property<int>("SessionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationUnitId");

                    b.ToTable("PredefinedComment");
                });

            modelBuilder.Entity("HyFive.Domain.Session.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<int?>("ObserverId")
                        .HasColumnType("integer");

                    b.Property<int>("OrganisationUnitId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TransferStatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("TransferStatusTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("Discriminator");

                    b.HasIndex("ObserverId");

                    b.HasIndex("OrganisationUnitId");

                    b.HasIndex("StartDate");

                    b.HasIndex("TransferStatusId");

                    b.HasIndex("TransferStatusTypeId");

                    b.ToTable("Session");

                    b.HasDiscriminator().HasValue("Session");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HyFive.Domain.Session.TransferStatusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("TransferStatusType");
                });

            modelBuilder.Entity("HyFive.Domain.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IdentityPseudonym")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityPseudonym");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HyFive.Domain.User.UserIdentifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserIdentifierTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("UserIdentifierTypeId");

                    b.HasIndex("UserId", "UserIdentifierTypeId")
                        .IsUnique();

                    b.ToTable("UserIdentifier", (string)null);
                });

            modelBuilder.Entity("HyFive.Domain.User.UserIdentifierType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("UserIdentifierType", (string)null);
                });

            modelBuilder.Entity("HyFive.Domain.User.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("OrganisationUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationUnitId");

                    b.HasIndex("UserId", "OrganisationUnitId")
                        .IsUnique();

                    b.ToTable("UserPermission");
                });

            modelBuilder.Entity("MisuseTypeProtectiveEquipment", b =>
                {
                    b.Property<int>("MisuseTypesId")
                        .HasColumnType("integer");

                    b.Property<int>("ProtectiveEquipmentId")
                        .HasColumnType("integer");

                    b.HasKey("MisuseTypesId", "ProtectiveEquipmentId");

                    b.HasIndex("ProtectiveEquipmentId");

                    b.ToTable("MisuseTypeProtectiveEquipment");
                });

            modelBuilder.Entity("HyFive.Domain.Session.FiveIndicationsSession", b =>
                {
                    b.HasBaseType("HyFive.Domain.Session.Session");

                    b.HasDiscriminator().HasValue("FiveIndicationsSession");
                });

            modelBuilder.Entity("HyFive.Domain.Session.GloveSession", b =>
                {
                    b.HasBaseType("HyFive.Domain.Session.Session");

                    b.HasDiscriminator().HasValue("GloveSession");
                });

            modelBuilder.Entity("HyFive.Domain.Session.HandJewelrySession", b =>
                {
                    b.HasBaseType("HyFive.Domain.Session.Session");

                    b.HasDiscriminator().HasValue("HandJewelrySession");
                });

            modelBuilder.Entity("HyFive.Domain.Session.ProtectiveEquipmentSession", b =>
                {
                    b.HasBaseType("HyFive.Domain.Session.Session");

                    b.HasDiscriminator().HasValue("ProtectiveEquipmentSession");
                });

            modelBuilder.Entity("FiveIndicationsObservationIndicationTypes", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.IndicationTypes", null)
                        .WithMany()
                        .HasForeignKey("IndicationTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.FiveIndicationsObservation", null)
                        .WithMany()
                        .HasForeignKey("ObservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GloveObservationGloveWithIndicationType", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.Gloves.GloveWithIndicationType", null)
                        .WithMany()
                        .HasForeignKey("GloveWithIndicationTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.Gloves.GloveObservation", null)
                        .WithMany()
                        .HasForeignKey("ObservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GloveObservationGloveWithoutIndicationType", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.Gloves.GloveWithoutIndicationType", null)
                        .WithMany()
                        .HasForeignKey("GloveWithoutIndicationTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.Gloves.GloveObservation", null)
                        .WithMany()
                        .HasForeignKey("ObservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HandJewelryObservationHandJewelryType", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.HandJewelryType", null)
                        .WithMany()
                        .HasForeignKey("HandJewelriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.HandJewelryObservation", null)
                        .WithMany()
                        .HasForeignKey("ObservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Activity", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.ActivityType", "ActivityType")
                        .WithMany()
                        .HasForeignKey("ActivityTypeId");

                    b.Navigation("ActivityType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.FiveIndicationsObservation", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId");

                    b.HasOne("HyFive.Domain.Session.FiveIndicationsSession", "FiveIndicationsSession")
                        .WithMany("Observations")
                        .HasForeignKey("FiveIndicationsSessionId");

                    b.HasOne("HyFive.Domain.Observation.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Activity");

                    b.Navigation("FiveIndicationsSession");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Gloves.GloveObservation", b =>
                {
                    b.HasOne("HyFive.Domain.Session.GloveSession", "GloveSession")
                        .WithMany("Observations")
                        .HasForeignKey("GloveSessionId");

                    b.HasOne("HyFive.Domain.Observation.Gloves.HandHygieneAfterGloveUseType", "PostGloveHandHygieneType")
                        .WithMany()
                        .HasForeignKey("PostGloveHandHygieneTypeId");

                    b.HasOne("HyFive.Domain.Observation.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("GloveSession");

                    b.Navigation("PostGloveHandHygieneType");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.HandJewelryObservation", b =>
                {
                    b.HasOne("HyFive.Domain.Session.HandJewelrySession", "HandJewelrySession")
                        .WithMany("Observations")
                        .HasForeignKey("HandJewelrySessionId");

                    b.HasOne("HyFive.Domain.Observation.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("HandJewelrySession");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.OrganisationUnitRole", b =>
                {
                    b.HasOne("HyFive.Domain.Place.OrganisationUnit", "OrganisationUnit")
                        .WithMany("OrganisationUnitRoles")
                        .HasForeignKey("OrganisationUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.Role", "Role")
                        .WithMany("OrganisationUnitRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrganisationUnit");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.MisuseType", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentType", "ProtectiveEquipmentType")
                        .WithMany("MisuseTypes")
                        .HasForeignKey("ProtectiveEquipmentTypeId");

                    b.Navigation("ProtectiveEquipmentType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipment", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentType", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId");

                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentObservation", "ProtectiveEquipmentObservation")
                        .WithMany("ProtectiveEquipmentList")
                        .HasForeignKey("ProtectiveEquipmentObservationId");

                    b.Navigation("EquipmentType");

                    b.Navigation("ProtectiveEquipmentObservation");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentObservation", b =>
                {
                    b.HasOne("HyFive.Domain.Session.ProtectiveEquipmentSession", "ProtectiveEquipmentSession")
                        .WithMany("Observations")
                        .HasForeignKey("ProtectiveEquipmentSessionId");

                    b.HasOne("HyFive.Domain.Observation.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentSettingType", "SettingType")
                        .WithMany()
                        .HasForeignKey("SettingTypeId");

                    b.Navigation("ProtectiveEquipmentSession");

                    b.Navigation("Role");

                    b.Navigation("SettingType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentSettingTypeProtectiveEquipmentType", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentSettingType", "ProtectiveEquipmentSettingType")
                        .WithMany("ProtectiveEquipmentSettingTypeProtectiveEquipmentTypes")
                        .HasForeignKey("ProtectiveEquipmentSettingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentType", "ProtectiveEquipmentType")
                        .WithMany("ProtectiveEquipmentSettingTypeProtectiveEquipmentTypes")
                        .HasForeignKey("ProtectiveEquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProtectiveEquipmentSettingTypeProtectiveEquipmentType_Prot~1");

                    b.Navigation("ProtectiveEquipmentSettingType");

                    b.Navigation("ProtectiveEquipmentType");
                });

            modelBuilder.Entity("HyFive.Domain.Place.Address", b =>
                {
                    b.HasOne("HyFive.Domain.Place.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("HyFive.Domain.Place.OrganisationUnit", b =>
                {
                    b.HasOne("HyFive.Domain.Place.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HyFive.Domain.Place.OrganisationUnitLevel", "LevelRef")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Place.OrganisationUnit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HyFive.Domain.Place.OrganisationUnitType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("LevelRef");

                    b.Navigation("Parent");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("HyFive.Domain.Place.OrganisationUnitAssociation", b =>
                {
                    b.HasOne("HyFive.Domain.Place.OrganisationUnit", "SourceOrganisationUnit")
                        .WithMany("OutgoingAssociations")
                        .HasForeignKey("SourceOrganisationUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Place.OrganisationUnit", "TargetOrganisationUnit")
                        .WithMany("IncomingAssociations")
                        .HasForeignKey("TargetOrganisationUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceOrganisationUnit");

                    b.Navigation("TargetOrganisationUnit");
                });

            modelBuilder.Entity("HyFive.Domain.Place.PredefinedComment", b =>
                {
                    b.HasOne("HyFive.Domain.Place.OrganisationUnit", "OrganisationUnit")
                        .WithMany()
                        .HasForeignKey("OrganisationUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganisationUnit");
                });

            modelBuilder.Entity("HyFive.Domain.Session.Session", b =>
                {
                    b.HasOne("HyFive.Domain.User.User", "Observer")
                        .WithMany()
                        .HasForeignKey("ObserverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HyFive.Domain.Place.OrganisationUnit", "OrganisationUnit")
                        .WithMany()
                        .HasForeignKey("OrganisationUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Session.TransferStatusType", "TransferStatus")
                        .WithMany()
                        .HasForeignKey("TransferStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HyFive.Domain.Session.TransferStatusType", null)
                        .WithMany("Sessions")
                        .HasForeignKey("TransferStatusTypeId");

                    b.Navigation("Observer");

                    b.Navigation("OrganisationUnit");

                    b.Navigation("TransferStatus");
                });

            modelBuilder.Entity("HyFive.Domain.User.UserIdentifier", b =>
                {
                    b.HasOne("HyFive.Domain.User.User", "User")
                        .WithMany("UserIdentifiers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.User.UserIdentifierType", "UserIdentifierType")
                        .WithMany()
                        .HasForeignKey("UserIdentifierTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserIdentifierType");
                });

            modelBuilder.Entity("HyFive.Domain.User.UserPermission", b =>
                {
                    b.HasOne("HyFive.Domain.Place.OrganisationUnit", "OrganisationUnit")
                        .WithMany()
                        .HasForeignKey("OrganisationUnitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HyFive.Domain.User.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrganisationUnit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MisuseTypeProtectiveEquipment", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.MisuseType", null)
                        .WithMany()
                        .HasForeignKey("MisuseTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipment", null)
                        .WithMany()
                        .HasForeignKey("ProtectiveEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentObservation", b =>
                {
                    b.Navigation("ProtectiveEquipmentList");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentSettingType", b =>
                {
                    b.Navigation("ProtectiveEquipmentSettingTypeProtectiveEquipmentTypes");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentType", b =>
                {
                    b.Navigation("MisuseTypes");

                    b.Navigation("ProtectiveEquipmentSettingTypeProtectiveEquipmentTypes");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Role", b =>
                {
                    b.Navigation("OrganisationUnitRoles");
                });

            modelBuilder.Entity("HyFive.Domain.Place.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("HyFive.Domain.Place.OrganisationUnit", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("IncomingAssociations");

                    b.Navigation("OrganisationUnitRoles");

                    b.Navigation("OutgoingAssociations");
                });

            modelBuilder.Entity("HyFive.Domain.Session.TransferStatusType", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("HyFive.Domain.User.User", b =>
                {
                    b.Navigation("UserIdentifiers");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("HyFive.Domain.Session.FiveIndicationsSession", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("HyFive.Domain.Session.GloveSession", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("HyFive.Domain.Session.HandJewelrySession", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("HyFive.Domain.Session.ProtectiveEquipmentSession", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
