// <auto-generated />
using System;
using HyFive.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HyFive.DataAccess.Migrations
{
    [DbContext(typeof(HandHygieneContext))]
    partial class HandHygieneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DepartmentRole", b =>
                {
                    b.Property<int>("DepartmentsId")
                        .HasColumnType("integer");

                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.HasKey("DepartmentsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("DepartmentRole");
                });

            modelBuilder.Entity("DepartmentUnit", b =>
                {
                    b.Property<int>("DepartmentsId")
                        .HasColumnType("integer");

                    b.Property<int>("UnitsId")
                        .HasColumnType("integer");

                    b.HasKey("DepartmentsId", "UnitsId");

                    b.HasIndex("UnitsId");

                    b.ToTable("DepartmentUnit");
                });

            modelBuilder.Entity("FiveIndicationsObservationIndicationTypes", b =>
                {
                    b.Property<int>("IndicationTypesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservationsId")
                        .HasColumnType("uuid");

                    b.HasKey("IndicationTypesId", "ObservationsId");

                    b.HasIndex("ObservationsId");

                    b.ToTable("FiveIndicationsObservationIndicationTypes");
                });

            modelBuilder.Entity("GloveObservationGloveWithIndicationType", b =>
                {
                    b.Property<int>("GloveWithIndicationTypesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservationsId")
                        .HasColumnType("uuid");

                    b.HasKey("GloveWithIndicationTypesId", "ObservationsId");

                    b.HasIndex("ObservationsId");

                    b.ToTable("GloveObservationGloveWithIndicationType");
                });

            modelBuilder.Entity("GloveObservationGloveWithoutIndicationType", b =>
                {
                    b.Property<int>("GloveWithoutIndicationTypesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservationsId")
                        .HasColumnType("uuid");

                    b.HasKey("GloveWithoutIndicationTypesId", "ObservationsId");

                    b.HasIndex("ObservationsId");

                    b.ToTable("GloveObservationGloveWithoutIndicationType");
                });

            modelBuilder.Entity("HandJewelryObservationHandJewelryType", b =>
                {
                    b.Property<int>("HandJewelriesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObservationsId")
                        .HasColumnType("uuid");

                    b.HasKey("HandJewelriesId", "ObservationsId");

                    b.HasIndex("ObservationsId");

                    b.ToTable("HandJewelryObservationHandJewelryType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityTypeId")
                        .HasColumnType("integer");

                    b.Property<bool?>("GlovesUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("SecondsUsed")
                        .HasColumnType("integer");

                    b.Property<bool>("TimingWasPerformed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("ActivityType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.FiveIndicationsObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FiveIndicationsSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegisteredTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("FiveIndicationsSessionId");

                    b.HasIndex("RegisteredTime");

                    b.HasIndex("RoleId");

                    b.ToTable("FiveIndicationsObservation");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Gloves.GloveObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GloveSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("GlovesUsed")
                        .HasColumnType("boolean");

                    b.Property<int?>("PostGloveHandHygieneTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegisteredTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("GloveSessionId");

                    b.HasIndex("PostGloveHandHygieneTypeId");

                    b.HasIndex("RegisteredTime");

                    b.HasIndex("RoleId");

                    b.ToTable("GloveObservation");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Gloves.GloveWithIndicationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("GloveWithIndicationType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Gloves.GloveWithoutIndicationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("GloveWithoutIndicationType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Gloves.HandHygieneAfterGloveUseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("HandHygieneAfterGloveUseType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.HandJewelryObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HandJewelrySessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegisteredTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("HandJewelrySessionId");

                    b.HasIndex("RegisteredTime");

                    b.HasIndex("RoleId");

                    b.ToTable("HandJewelryObservation");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.HandJewelryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("HandJewelryType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.IndicationTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Number")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("IndicationType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.MisuseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ProtectiveEquipmentTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ProtectiveEquipmentTypeId");

                    b.ToTable("MisuseType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("EquipmentTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProtectiveEquipmentObservationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasUsed")
                        .HasColumnType("boolean");

                    b.Property<bool>("WasUsedCorrectly")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("ProtectiveEquipmentObservationId");

                    b.ToTable("ProtectiveEquipment");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProtectiveEquipmentSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegisteredTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int?>("SettingTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("ProtectiveEquipmentSessionId");

                    b.HasIndex("RegisteredTime");

                    b.HasIndex("RoleId");

                    b.HasIndex("SettingTypeId");

                    b.ToTable("ProtectiveEquipmentObservation");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentSettingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("ProtectiveEquipmentSettingType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentSettingTypeProtectiveEquipmentType", b =>
                {
                    b.Property<int>("ProtectiveEquipmentTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ProtectiveEquipmentSettingTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.HasKey("ProtectiveEquipmentTypeId", "ProtectiveEquipmentSettingTypeId");

                    b.HasIndex("ProtectiveEquipmentSettingTypeId");

                    b.ToTable("ProtectiveEquipmentSettingTypeProtectiveEquipmentType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("ProtectiveEquipmentType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("HyFive.Domain.Place.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("HyFive.Domain.Place.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("FacilityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentTypeId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("Name");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("HyFive.Domain.Place.DepartmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("DepartmentType");
                });

            modelBuilder.Entity("HyFive.Domain.Place.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FacilityTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("HERId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation");

                    b.HasIndex("CityId");

                    b.HasIndex("FacilityTypeId");

                    b.HasIndex("HERId");

                    b.HasIndex("Name");

                    b.ToTable("Facility");
                });

            modelBuilder.Entity("HyFive.Domain.Place.FacilityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("FacilityType");
                });

            modelBuilder.Entity("HyFive.Domain.Place.PredefinedComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FacilityId")
                        .HasColumnType("integer");

                    b.Property<int>("SessionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("PredefinedComment");
                });

            modelBuilder.Entity("HyFive.Domain.Place.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FacilityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("Name");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("HyFive.Domain.Session.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<int?>("ObserverId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TransferStatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Discriminator");

                    b.HasIndex("ObserverId");

                    b.HasIndex("StartDate");

                    b.HasIndex("TransferStatusId");

                    b.ToTable("Session");

                    b.HasDiscriminator().HasValue("Session");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HyFive.Domain.Session.TransferStatusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("TransferStatusType");
                });

            modelBuilder.Entity("HyFive.Domain.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HPRNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IdentityPseudonym")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeactivated")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("HPRNumber");

                    b.HasIndex("IdentityPseudonym");

                    b.ToTable("User");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MisuseTypeProtectiveEquipment", b =>
                {
                    b.Property<int>("MisuseTypesId")
                        .HasColumnType("integer");

                    b.Property<int>("ProtectiveEquipmentId")
                        .HasColumnType("integer");

                    b.HasKey("MisuseTypesId", "ProtectiveEquipmentId");

                    b.HasIndex("ProtectiveEquipmentId");

                    b.ToTable("MisuseTypeProtectiveEquipment");
                });

            modelBuilder.Entity("HyFive.Domain.Session.FiveIndicationsSession", b =>
                {
                    b.HasBaseType("HyFive.Domain.Session.Session");

                    b.HasDiscriminator().HasValue("FiveIndicationsSession");
                });

            modelBuilder.Entity("HyFive.Domain.Session.GloveSession", b =>
                {
                    b.HasBaseType("HyFive.Domain.Session.Session");

                    b.HasDiscriminator().HasValue("GloveSession");
                });

            modelBuilder.Entity("HyFive.Domain.Session.HandJewelrySession", b =>
                {
                    b.HasBaseType("HyFive.Domain.Session.Session");

                    b.HasDiscriminator().HasValue("HandJewelrySession");
                });

            modelBuilder.Entity("HyFive.Domain.Session.ProtectiveEquipmentSession", b =>
                {
                    b.HasBaseType("HyFive.Domain.Session.Session");

                    b.HasDiscriminator().HasValue("ProtectiveEquipmentSession");
                });

            modelBuilder.Entity("HyFive.Domain.User.Admin", b =>
                {
                    b.HasBaseType("HyFive.Domain.User.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("HyFive.Domain.User.Coordinator", b =>
                {
                    b.HasBaseType("HyFive.Domain.User.User");

                    b.HasDiscriminator().HasValue("Coordinator");
                });

            modelBuilder.Entity("HyFive.Domain.User.Observer", b =>
                {
                    b.HasBaseType("HyFive.Domain.User.User");

                    b.HasDiscriminator().HasValue("Observer");
                });

            modelBuilder.Entity("DepartmentRole", b =>
                {
                    b.HasOne("HyFive.Domain.Place.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DepartmentUnit", b =>
                {
                    b.HasOne("HyFive.Domain.Place.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Place.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FiveIndicationsObservationIndicationTypes", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.IndicationTypes", null)
                        .WithMany()
                        .HasForeignKey("IndicationTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.FiveIndicationsObservation", null)
                        .WithMany()
                        .HasForeignKey("ObservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GloveObservationGloveWithIndicationType", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.Gloves.GloveWithIndicationType", null)
                        .WithMany()
                        .HasForeignKey("GloveWithIndicationTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.Gloves.GloveObservation", null)
                        .WithMany()
                        .HasForeignKey("ObservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GloveObservationGloveWithoutIndicationType", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.Gloves.GloveWithoutIndicationType", null)
                        .WithMany()
                        .HasForeignKey("GloveWithoutIndicationTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.Gloves.GloveObservation", null)
                        .WithMany()
                        .HasForeignKey("ObservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HandJewelryObservationHandJewelryType", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.HandJewelryType", null)
                        .WithMany()
                        .HasForeignKey("HandJewelriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.HandJewelryObservation", null)
                        .WithMany()
                        .HasForeignKey("ObservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Activity", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.ActivityType", "ActivityType")
                        .WithMany()
                        .HasForeignKey("ActivityTypeId");

                    b.Navigation("ActivityType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.FiveIndicationsObservation", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId");

                    b.HasOne("HyFive.Domain.Session.FiveIndicationsSession", "FiveIndicationsSession")
                        .WithMany("Observations")
                        .HasForeignKey("FiveIndicationsSessionId");

                    b.HasOne("HyFive.Domain.Observation.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Activity");

                    b.Navigation("FiveIndicationsSession");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.Gloves.GloveObservation", b =>
                {
                    b.HasOne("HyFive.Domain.Session.GloveSession", "GloveSession")
                        .WithMany("Observations")
                        .HasForeignKey("GloveSessionId");

                    b.HasOne("HyFive.Domain.Observation.Gloves.HandHygieneAfterGloveUseType", "PostGloveHandHygieneType")
                        .WithMany()
                        .HasForeignKey("PostGloveHandHygieneTypeId");

                    b.HasOne("HyFive.Domain.Observation.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("GloveSession");

                    b.Navigation("PostGloveHandHygieneType");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.HandJewelryObservation", b =>
                {
                    b.HasOne("HyFive.Domain.Session.HandJewelrySession", "HandJewelrySession")
                        .WithMany("Observations")
                        .HasForeignKey("HandJewelrySessionId");

                    b.HasOne("HyFive.Domain.Observation.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("HandJewelrySession");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.MisuseType", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentType", "ProtectiveEquipmentType")
                        .WithMany("MisuseTypes")
                        .HasForeignKey("ProtectiveEquipmentTypeId");

                    b.Navigation("ProtectiveEquipmentType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipment", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentType", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId");

                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentObservation", "ProtectiveEquipmentObservation")
                        .WithMany("ProtectiveEquipmentList")
                        .HasForeignKey("ProtectiveEquipmentObservationId");

                    b.Navigation("EquipmentType");

                    b.Navigation("ProtectiveEquipmentObservation");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentObservation", b =>
                {
                    b.HasOne("HyFive.Domain.Session.ProtectiveEquipmentSession", "ProtectiveEquipmentSession")
                        .WithMany("Observations")
                        .HasForeignKey("ProtectiveEquipmentSessionId");

                    b.HasOne("HyFive.Domain.Observation.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentSettingType", "SettingType")
                        .WithMany()
                        .HasForeignKey("SettingTypeId");

                    b.Navigation("ProtectiveEquipmentSession");

                    b.Navigation("Role");

                    b.Navigation("SettingType");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentSettingTypeProtectiveEquipmentType", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentSettingType", "ProtectiveEquipmentSettingType")
                        .WithMany("ProtectiveEquipmentSettingTypeProtectiveEquipmentTypes")
                        .HasForeignKey("ProtectiveEquipmentSettingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentType", "ProtectiveEquipmentType")
                        .WithMany("ProtectiveEquipmentSettingTypeProtectiveEquipmentTypes")
                        .HasForeignKey("ProtectiveEquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProtectiveEquipmentSettingTypeProtectiveEquipmentType_Prot~1");

                    b.Navigation("ProtectiveEquipmentSettingType");

                    b.Navigation("ProtectiveEquipmentType");
                });

            modelBuilder.Entity("HyFive.Domain.Place.Department", b =>
                {
                    b.HasOne("HyFive.Domain.Place.DepartmentType", "DepartmentType")
                        .WithMany()
                        .HasForeignKey("DepartmentTypeId");

                    b.HasOne("HyFive.Domain.Place.Facility", "Facility")
                        .WithMany("Departments")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentType");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("HyFive.Domain.Place.Facility", b =>
                {
                    b.HasOne("HyFive.Domain.Place.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("HyFive.Domain.Place.FacilityType", "FacilityType")
                        .WithMany()
                        .HasForeignKey("FacilityTypeId");

                    b.Navigation("City");

                    b.Navigation("FacilityType");
                });

            modelBuilder.Entity("HyFive.Domain.Place.PredefinedComment", b =>
                {
                    b.HasOne("HyFive.Domain.Place.Facility", null)
                        .WithMany("PredefinedComment")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyFive.Domain.Place.Unit", b =>
                {
                    b.HasOne("HyFive.Domain.Place.Facility", "Facility")
                        .WithMany("Units")
                        .HasForeignKey("FacilityId");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("HyFive.Domain.Session.Session", b =>
                {
                    b.HasOne("HyFive.Domain.Place.Department", "Department")
                        .WithMany("Sessions")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("HyFive.Domain.User.User", "Observer")
                        .WithMany()
                        .HasForeignKey("ObserverId");

                    b.HasOne("HyFive.Domain.Session.TransferStatusType", "TransferStatus")
                        .WithMany("Sessions")
                        .HasForeignKey("TransferStatusId");

                    b.Navigation("Department");

                    b.Navigation("Observer");

                    b.Navigation("TransferStatus");
                });

            modelBuilder.Entity("HyFive.Domain.User.User", b =>
                {
                    b.HasOne("HyFive.Domain.Place.Facility", "Facility")
                        .WithMany("Users")
                        .HasForeignKey("FacilityId");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("MisuseTypeProtectiveEquipment", b =>
                {
                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.MisuseType", null)
                        .WithMany()
                        .HasForeignKey("MisuseTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipment", null)
                        .WithMany()
                        .HasForeignKey("ProtectiveEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentObservation", b =>
                {
                    b.Navigation("ProtectiveEquipmentList");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentSettingType", b =>
                {
                    b.Navigation("ProtectiveEquipmentSettingTypeProtectiveEquipmentTypes");
                });

            modelBuilder.Entity("HyFive.Domain.Observation.ProtectiveEquipment.ProtectiveEquipmentType", b =>
                {
                    b.Navigation("MisuseTypes");

                    b.Navigation("ProtectiveEquipmentSettingTypeProtectiveEquipmentTypes");
                });

            modelBuilder.Entity("HyFive.Domain.Place.Department", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("HyFive.Domain.Place.Facility", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("PredefinedComment");

                    b.Navigation("Units");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HyFive.Domain.Session.TransferStatusType", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("HyFive.Domain.Session.FiveIndicationsSession", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("HyFive.Domain.Session.GloveSession", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("HyFive.Domain.Session.HandJewelrySession", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("HyFive.Domain.Session.ProtectiveEquipmentSession", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
