apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "HyFive.fullname" . }}-admin
  labels:
    {{- include "HyFive.labels" . | nindent 4 }}
data:
  RedirectPagesSettings__RedirectLogInUri: {{ .Values.oidc.redirects.admin.login }}
  RedirectPagesSettings__RedirectLogOutUri: {{ .Values.oidc.redirects.admin.logout }}
  RedirectPagesSettings__LoggedOut: {{ .Values.oidc.redirects.admin.loggedout }}
  RedirectPagesSettings__LoggedIn: {{ .Values.oidc.redirects.admin.loggedin }}
