apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "HyFive.fullname" . }}-admin
  labels:
    {{- include "HyFive.adminLabels" . | nindent 4 }}
spec:
  {{- if not .Values.admin.autoscaling.enabled }}
  replicas: {{ .Values.admin.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "HyFive.adminSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "HyFive.adminLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "HyFive.serviceAccountName" . }}
      {{- with .Values.admin.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.admin.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.global.image_repository }}{{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.admin.image.pullPolicy }}
          env:
          - name: ConnectionStrings__HandhygieneConnection
            value: Server=$(POSTGRES_HOST); Database=$(POSTGRES_DB); Username=$(POSTGRES_USER); Password=$(POSTGRES_PASSWORD); SSLMode=disable
          envFrom:
            - secretRef:
                name: {{ include "HyFive.fullname" . }}-db
            - secretRef:
                name: {{ include "HyFive.fullname" . }}-oidc
            - configMapRef:
                name: {{ include "HyFive.fullname" . }}-admin
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe: {}
          # readinessProbe: {}
          {{- with .Values.admin.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.admin.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.admin.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admin.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admin.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admin.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
