<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="AutoMapper" Version="13.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HyFive.DataAccess\HyFive.DataAccess.csproj" />
    <ProjectReference Include="..\HyFive.Domain\HyFive.Domain.csproj" />
    <ProjectReference Include="..\HyFive.Models\HyFive.Models.csproj" />
    <ProjectReference Include="..\HyFive.Services.Authentication\HyFive.Services.Authentication.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Overforingsstatus\" />
    <Folder Include="Report\NewFolder\" />
  </ItemGroup>
</Project>