//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export abstract class ActivityTypeConstants
{
	public static Disinfection: string = `DISINFECTION`;
	public static HandWashing: string = `HANDWASHING`;
	public static NotRequired: string = `NOTREQUIRED`;
	public static NotRegistered: string = `NOTREGISTERED`;
}
