//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export abstract class ActivityTypeConstants
{
	public static Disinfection: string = `DISINFECTION`;
	public static Handwash: string = `HANDWASH`;
	public static NotPerformed: string = `NOT_PERFORMED`;
	public static NotRegistered: string = `NOT_REGISTERED`;
}
