//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { ActivityType } from './ActivityType';

export interface Activity
{
	activityType: ActivityType;
	secondsUsed?: number;
	timekeepingWasRemoved: boolean;
	usedGlove?: boolean;
}
