//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { FacilityReport } from './FacilityReport';
import { UserIdentifier } from './UserIdentifier';
import { UpdateUserIdentifierRequest } from './UpdateUserIdentifierRequest';

export interface CityCoordinator
{
	id: number;
	createdTime: any;
	firstName: string;
	lastName: string;
	email: string;
	identityPseudonym: string;
	isDeactivated: boolean;
	facilities: FacilityReport[];
	modifiedPseudonym?: string;
	userIdentifiers?: UserIdentifier[];
	modifiedIdentifiers?: UpdateUserIdentifierRequest[];
}
