//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { InstitutionReport } from './InstitutionReport';

export interface CoordinatorForHealthcareEnterprises
{
	timeOfCreation: any;
	firstName: string;
	lastName: string;
	email: string;
	identityPseudonym: string;
	isDisabled: boolean;
	hprNummer: string;
	institutions: InstitutionReport[];
	changedIdentityPseudonym?: string;
	changedHPRNumber?: string;
}
