//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { InstitutionReport } from './InstitutionReport';

export interface CoordinatorForHealthcareOrganization
{
	id?: number,
	createdTime: any;
	firstName: string;
	lastName: string;
	email: string;
	identityPseudonym: string;
	isDisabled: boolean;
	hprNumber: string;
	institutions: InstitutionReport[];
	modifiedPseudonym?: string;
	modifiedHPRNumber?: string;
}
