//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface CreateInstitutionRequest
{
	institutionName: string;
	abbreviation: string;
	herId: string;
	institutionTypeId: number;
	coordinatorHPRNumber: string;
	coordinatorPseudonym: string;
	coordinatorFirstName: string;
	coordinatorLastName: string;
	coordinatorEmail: string;
	regionId: number;
	municipalityId: number;
	institutionId: number;
}
