//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface CreateFacilityRequest
{
	name: string;
	abbreviation: string;
	description: string;
	organisationUnitTypeId: number;
	city: string;
	street: string;
	postalCode: string;
	firstName: string;
	lastName: string;
	email: string;
	pseudonym: string;
}