//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Role } from './Role';
import { AvdelingType } from './AvdelingType';

export interface Department
{
	id: number;
	institutionId: number;
	departmentTypeId: number;
	name: string;
	roles: Role[];
	departmentType: AvdelingType;
}
