//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { FacilityType } from './FacilityType';
import { City } from './City';

export interface FacilityReport
{
	id: number;
	name: string;
	abbreviation: string;
	herId: string;
	facilityType: FacilityType;
	city: City;
}
