//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Department } from './Department';
import { FacilityType } from './FacilityType';
import { City } from './City';

export interface Facility
{
	id: number;
	name: string;
	abbreviation: string;
	herId: string;
	departments: Department[];
	facilityType: FacilityType;
	hasObservations: boolean;
	city: City;
}
