//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export abstract class FacilityTypeConstants
{
	public static PrimaryCare: string = `PRIMARY_CARE`;
	public static SecondaryCare: string = `SECONDARY_CARE`;
	public static TertiaryCare: string = `TERTIARY_CARE`;
	public static SpecialisedCare: string = `SPECIALISED_CARE`;
	public static LongTermCare: string = `LONG_TERM_CARE`;
}
