//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface ForesporselOmBrukertilgang
{
	id: number;
	institutionId?: number;
	brukerFornavn: string;
	brukerEtternavn: string;
	identityPseudonym: string;
	hprNumber: string;
	status: number;
	timeOfCreation: any;
	godkjenttidspunkt: any;
}
