//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { FourIndicatorsObservation } from './FourIndicatorsObservation';
import { Session } from './Session';

export interface FourIndicationsSession extends Session<FourIndicatorsObservation>
{
}
