//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Observation } from './Observation';
import { GloveWithIndicationType } from './GloveWithIndicationType';
import { GloveWithoutIndicationType } from './GloveWithoutIndicationType';
import { HandHygieneAfterGloveUseType } from './HandHygieneAfterGloveUseType';

export interface GloveObservation extends Observation
{
	gloveWithIndicationTypes?: GloveWithIndicationType[];
	gloveWithoutIndicationTypes?: GloveWithoutIndicationType[];
	usedGlove: boolean;
	handhygieneAfterGloveuseType?: HandHygieneAfterGloveUseType;
}
