//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class GloveWithIndicationTypeConstants
{
	public static BodyFluids: string = `BODY_FLUIDS`;
	public static Transmission: string = `TRANSMISSION`;
	public static Other: string = `OTHER`;
}
