//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Observation } from './Observation';
import { IndicatedGloveType } from './IndicatedGloveType';
import { GloveWithoutIndicationType } from './GloveWithoutIndicationType';
import { PostGloveHandHygieneType } from './PostGloveHandHygieneType';

export interface GloveObservation extends Observation
{
	indicatedGloveTypes?: IndicatedGloveType[];
	gloveWithoutIndicationType?: GloveWithoutIndicationType[];
	gloveUsed: boolean;
	postGloveHandHygieneType?: PostGloveHandHygieneType;
}
