//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Observation } from './Observation';
import { IndicationType } from './IndicationType';
import { Activity } from './Activity';

export interface HandHygieneObservation extends Observation
{
	indicationTypes?: IndicationType[];
	activity?: Activity;
}
