//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { BraceletObservation } from './BraceletObservation';
import { Sesjon } from './Sesjon';

export interface HandsmykkeSesjon extends Sesjon<BraceletObservation>
{
}
