//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { GloveObservation } from './GloveObservation';
import { Sesjon } from './Sesjon';

export interface HanskeSesjon extends Sesjon<GloveObservation>
{
}
