//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { RegionalHealthcareOrganization } from './RegionalHealthcareOrganization';

export interface HealthcareOrganisation
{
	id: number;
	name: string;
	regionalHealthcareOrganisationId: number;
	regionaltHelseforetak: RegionalHealthcareOrganization;
}
