"use strict";
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
Object.defineProperty(exports, "__esModule", { value: true });
exports.IndicationTypeConstants = void 0;
var IndicationTypeConstants = /** @class */ (function () {
    function IndicationTypeConstants() {
    }
    IndicationTypeConstants.BeforePatient = "BEFORE_PATIENT";
    IndicationTypeConstants.AsepticProcedures = "ASEPTIC_PROCEDURES";
    IndicationTypeConstants.BodyFluid = "BODY_FLUID";
    IndicationTypeConstants.AfterPatient = "AFTER_PATIENT";
    IndicationTypeConstants.PatientsSurroundings = "PATIENTS_SURROUNDINGS";
    return IndicationTypeConstants;
}());
exports.IndicationTypeConstants = IndicationTypeConstants;
//# sourceMappingURL=IndicationTypeConstants.js.map