//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface InnloggetBruker
{
	id: string;
	identityPseudonym: string;
	name: string;
	erKoordinator: boolean;
	erFhiAdmin: boolean;
	erObservator: boolean;
	institusjonsIder: number[];
	firstName: string;
	lastName: string;
	hprNummer: string;
}
