//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { AvdelingOversiktRapport } from './AvdelingOversiktRapport';

export interface InstitutionOverviewReport
{
	id: number;
	name: string;
	numberSessions: number;
	numberObservations: number;
	departments: AvdelingOversiktRapport[];
}
