//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Department} from './Department';
import { InstitutionType } from './InstitutionType';
import { Region } from './Region';
import { Municipality } from './Municipality';
import { HealthcareEnterprise } from './HealthcareEnterprise';

export interface Institution
{
	id: number;
	name: string;
	abbreviation: string;
	herId: string;
	departments: Department[];
	institutionType: InstitutionType;
	region: Region;
	municipality: Municipality;
	hasObservations: boolean;
	healthcareEnterprise: HealthcareEnterprise;
}
