//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { InstitutionType } from './InstitutionType';
import { Region } from './Region';
import { Comment } from './Comment';
import { HealthcareOrganization } from './HealthcareOrganization';

export interface InstitutionReport
{
	id: number;
	name: string;
	abbreviation: string;
	herId: string;
	institutionType: InstitutionType;
	region: Region;
	comment: Comment;
	healthcareEnterprise: HealthcareOrganization;
}
