//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { InstitutionType } from './InstitutionType';
import { Region } from './Region';
import { Kommune } from './Kommune';
import { Helseforetak } from './Helseforetak';

export interface InstitutionReport
{
	id: number;
	name: string;
	abbreviation: string;
	herId: string;
	institutionType: InstitutionType;
	region: Region;
	municipality: Kommune;
	healthcareCompany: Helseforetak;
}
