//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface LoggedinUser
{
	id: string;
	identityPseudonym: string;
	name: string;
	isCoordinator: boolean;
	isFhiAdmin: boolean;
	isObserver: boolean;
	institutionIds: number[];
	firstName: string;
	lastName: string;
	hprNumber: string;
}
