//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Role } from './Role';
import { IndicationType } from './IndicationType';
import { Activity } from './Activity';
import { HandsmykkeType } from './HandsmykkeType';
import { BeskyttelsesutstyrOversiktRapport } from './BeskyttelsesutstyrOversiktRapport';
import { GloveObservation } from './GloveObservation';
import { ProtectiveEquipmentObservation } from './ProtectiveEquipmentObservation';

export interface ObservasjonOversiktRapport
{
	id: any;
	rolle: Role;
	kommentar: string;
	registrerttidspunkt: any;
	indikasjonstyper: IndicationType[];
	activity: Activity;
	handsmykketyper: HandsmykkeType[];
	beskyttelsesutstyrsetting: string;
	beskyttelsesutstyr: BeskyttelsesutstyrOversiktRapport[];
	hanskeObservasjon: GloveObservation;
	beskyttelsesutstyrObservasjon: ProtectiveEquipmentObservation;
}
