//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Role } from './Role';
import { IndicationType } from './IndicationType';
import { Activity } from './Activity';
import { HandJewelryType } from './HandJewelryType';
import { ProtectiveEquipmentOverviewReport } from './ProtectiveEquipmentOverviewReport';
import { GloveObservation } from './GloveObservation';
import { ProtectiveEquipmentObservation } from './ProtectiveEquipmentObservation';

export interface ObservationOverviewReport
{
	id: any;
	role: Role;
	comment: string;
	registeredTime: any;
	indicationTypes: IndicationType[];
	activity: Activity;
	handJewelryTypes: HandJewelryType[];
	protectiveEquipmentSettingTypeProtectiveEquipmentTypes: string;
	protectiveEquipment: ProtectiveEquipmentOverviewReport[];
	gloveObservation: GloveObservation;
	protectiveEquipmentObservation: ProtectiveEquipmentObservation;
}
