//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Role } from './Role';
import { IndicationType } from './IndicationType';
import { Activity } from './Activity';
import { BraceletType } from './BraceletType';
import { BeskyttelsesutstyrOversiktRapport } from './BeskyttelsesutstyrOversiktRapport';
import { GloveObservation } from './GloveObservation';
import { ProtectiveEquipmentObservation } from './ProtectiveEquipmentObservation';

export interface ObservationOverviewReport
{
	id: any;
	role: Role;
	comment: string;
	registrationTime: any;
	indicationTypes: IndicationType[];
	activity: Activity;
	typesOfHandJewelry: BraceletType[];
	protectiveEquipmentSetting: string;
	protectiveEquipment: BeskyttelsesutstyrOversiktRapport[];
	gloveObservation: GloveObservation;
	protectiveEquipmentObservation: ProtectiveEquipmentObservation;
}
