//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { OrganisationUnitLevel } from './OrganisationUnitLevel';
import { OrganisationUnitType } from './OrganisationUnitType';
import { Address } from './Address';
import { Role } from './Role';

export interface OrganisationUnit
{
	id: number;
	parentId: number;
	name: string;
	abbreviation: string;
	description: string;
	levelId: number;
	levelRef: OrganisationUnitLevel;
	typeId: number;
	type: OrganisationUnitType;
	addressId: number;
	address: Address;
	children: OrganisationUnit[];
	roles: Role[];
	hasObservations: boolean;
}
