//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.


import { Observation } from './Observation';
import { ProtectiveEquipment } from './ProtectiveEquipment';
import { ProtectiveEquipmentType } from './ProtectiveEquipmentType';

export interface ProtectiveEquipmentObservation extends Observation
{
	protectiveEquipmentList: ProtectiveEquipment[];
	settingtype: ProtectiveEquipmentType;
}
