//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class ProtectiveEquipmentTypeConstants
{
	public static Gloves: string = `GLOVES`;
	public static InfectiousCoat: string = `INFECTIOUSCOAT`;
	public static FaceMask: string = `FACEMASK`;
	public static EyeProtection: string = `EYEPROTECTION`;
	public static RespiratoryProtection: string = `RESPIRATORYPROTECTION`;
	public static Hood: string = `HOOD`;
	public static PlasticApron: string = `PLASTICAPRON`;
	public static ChangingCoat: string = `CHANGINGCOAT`;
}
