//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { ProtectiveEquipmentType } from './ProtectiveEquipmentType';
import { MisuseType } from './MisuseType';

export interface ProtectiveEquipment
{
	id: number;
	wasUsed: boolean;
	isIndicated: boolean;
	equipmentType: ProtectiveEquipmentType;
	misuseTypes: MisuseType[];
	wasUsedCorrectly: boolean;
	comment: string;
}
