"use strict";
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProtectiveEquipmentSettingTypeConstants = void 0;
var ProtectiveEquipmentSettingTypeConstants = /** @class */ (function () {
    function ProtectiveEquipmentSettingTypeConstants() {
    }
    ProtectiveEquipmentSettingTypeConstants.BasicIsolationRoutines = "BASIC_ISOLATION_ROUTINES";
    ProtectiveEquipmentSettingTypeConstants.ContactTransmission = "CONTACT_TRANSMISSION";
    ProtectiveEquipmentSettingTypeConstants.DropletTransmission = "DROPLET_TRANSMISSION";
    ProtectiveEquipmentSettingTypeConstants.AirborneTransmission = "AIRBORNE_TRANSMISSION";
    return ProtectiveEquipmentSettingTypeConstants;
}());
exports.ProtectiveEquipmentSettingTypeConstants = ProtectiveEquipmentSettingTypeConstants;
//# sourceMappingURL=ProtectiveEquipmentSettingTypeConstants.js.map