//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { ProtectiveEquipmentTypeq } from './ProtectiveEquipmentTypeq';

export interface ProtectiveEquipmentType
{
	id: number;
	code: string;
	name: string;
	equipmentTypeqs: ProtectiveEquipmentTypeq[];
}
