//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.


import { Observation } from './Observation';
import { Beskyttelsesutstyr } from './Beskyttelsesutstyr';
import { BeskyttelsesutstyrsettingType } from './BeskyttelsesutstyrsettingType';

export interface ProtectiveEquipmentObservation extends Observation
{
	beskyttelsesutstyrliste: Beskyttelsesutstyr[];
	settingtype: BeskyttelsesutstyrsettingType;
}
