//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class ProtectiveEquipmentTypeConstants
{
	public static Gloves: string = `GLOVES`;
	public static IsolationGown: string = `ISOLATION_GOWN`;
	public static FaceMask: string = `FACE_MASK`;
	public static EyeProtection: string = `EYE_PROTECTION`;
	public static RespiratoryProtection: string = `RESPIRATORY_PROTECTION`;
	public static Hood: string = `HOOD`;
	public static PlasticApron: string = `PLASTIC_APRON`;
	public static CareGown: string = `CARE_GOWN`;
}
