//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Department} from './Department';

export interface Sesjon<TObservasjon>
{
	id: string;
	avdeling: Department;
	starttidspunkt: Date;
	observasjoner?: TObservasjon[];
	institusjonsnavn?: string;
	institutionId?: number;
	kommentar?: string;
}
