//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Department } from './Department';
import { ObservationOverviewReport } from './ObservationOverviewReport';

export interface SessionOverviewReport
{
	id: any;
	type: string;
	observerName: string;
	department: Department;
	startDate: any;
	createdDate: any;
	comment: string;
	transferStatus: any;
	observations: ObservationOverviewReport[];
	isSelected: boolean;
}
