//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { ObservationOverviewReport } from './ObservationOverviewReport';

export interface SessionOverviewReport
{
	id: any;
	type: string;
	typeName: string;
	observerName: string;
	unitName: string;
	departmentName: string;
	departmentId: number;
	facilityId: number;
	startDate: any;
	createdDate: any;
	comment: string;
	transferStatus: any;
	observations: ObservationOverviewReport[];
	isSelected: boolean;
}
