//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { SessionType } from './SessionType';

export interface SessionReport
{
	id: string;
	unitId: number;
	unitName: string;
	departmentId: number;
	departmentName: string;
	facilityId: number;
	facilityName: string;
	startDate: any;
	type: SessionType;
	typeName: string;
	isSelected?: boolean;
}
