//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class TransferStatusTypeConstants
{
	public static TransferredToAdmin: string = `TRANSFERRED_TO_ADMIN`;
	public static TransferredToCoordinator: string = `TRANSFERRED_TO_COORDINATOR`;
}
