//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class TransferstatusTypeConstants
{
	public static TransferToFhi: string = `TRANSFER_TO_FHI`;
	public static TransferToCoordinator: string = `TRANSFER_TO_COORDINATOR`;
}
