//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface UnitOverviewReport
{
	id: number;
	name: string;
	numberOfSessions: number;
	numberOfObservations: number;
	departmentName: string;
	departmentId: number;
}
