//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface UserAccessRequest
{
	id: number;
	institutionId?: number;
	userFirstName: string;
	userLastName: string;
	identityPseudonym: string;
	hprNumber: string;
	status: number;
	createdTime: any;
	approvedTime: any;
}
