//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { OrganisationUnit } from './OrganisationUnit';

export interface UserPermission
{
	id: number;
	permissionLevel: string;
	userId: number;
	organisationUnitId: number;
	organisationUnit?: OrganisationUnit;
}
