//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface User
{
	id: number;
	institutionId: number;
	createdTime: any;
	firstName: string;
	lastName: string;
	email: string;
	identityPseudonym: string;
	isDisabled: boolean;
	hprNumber: string;
}
