//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { UserIdentifierType } from './UserIdentifierType';

export interface UserIdentifier
{
	id: number;
	identifierType: string;
	value: string;
	userId: number;
	userIdentifierTypeId: number;
	userIdentifierType?: UserIdentifierType;
}
