//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Department } from './Department';

export interface Clinic
{
	id: number;
	facilityId: number;
	name: string;
	departments: Department[];
}
