//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { FacilityType } from './FacilityType';
import { Region } from './Region';
import { Municipality } from './Municipality';
import { HealthcareOrganization } from './HealthcareOrganization';

export interface FacilityReport
{
	id: number;
	name: string;
	abbreviation: string;
	herId: string;
	facilityType: FacilityType;
	region: Region;
	municipality: Municipality;
	healthcareOrganization: HealthcareOrganization;
}
