//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { OrganisationUnitType } from "./OrganisationUnitType";


export interface FacilityReport
{
	id: number;
	name: string;
	abbreviation: string;
	type: OrganisationUnitType;
	city: string;
}
