//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class GloveWithoutIndicationTypeConstants
{
	public static CareWithoutBodyFluids: string = `CARE_WITHOUT_BODY_FLUIDS`;
	public static Food: string = `FOOD`;
	public static Other: string = `OTHER`;
}
