//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export abstract class HandJewelryTypeConstants
{
	public static AllOk: string = `ALL_OK`;
	public static Ring: string = `RING`;
	public static WatchBracelet: string = `WATCH_BRACELET`;
	public static LongNail: string = `LONG_NAILS`;
	public static ArtificialNailShellac: string = `ARTIFICIAL_NAIL_SHELLAC`;
	public static ShortSleeves: string = `SHORT_SLEEVES`;
	public static LongSleeves: string = `LONG_SLEEVES`;
}
