//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { HandJewelryObservation } from './HandJewelryObservation';
import { Session } from './Session';

export interface HandJewelrySession extends Session<HandJewelryObservation>
{
}
