//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { HandHygieneObservation } from './HandHygieneObservation';
import { Session } from './Session';

export interface HandHygieneSession extends Session<HandHygieneObservation>
{
}
