//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class HandHygieneAfterGloveUseTypeConstants
{
	public static Yes: string = `YES`;
	public static No: string = `NO`;
	public static NotIndicated: string = `NOT_INDICATED`;
}
