//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export abstract class IndicationTypeConstants
{
	public static BeforePatient: string = `BEFORE_PATIENT`;
	public static AsepticProcedures: string = `ASEPTIC_PROCEDURES`;
	public static BodyFluid: string = `BODY_FLUID`;
	public static AfterPatient: string = `AFTER_PATIENT`;
	public static PatientsSurroundings = `PATIENTS_SURROUNDINGS`;
}
