"use strict";
//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=Institution.js.map