//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { OrganisationUnit } from "./OrganisationUnit";

export interface LoggedInUser
{
	id: string;
	identityPseudonym: string;
	name: string;
	isCoordinator: boolean;
	isAdmin: boolean;
	isObserver: boolean;
	organisationUnits: OrganisationUnit[];
	firstName: string;
	lastName: string;
	email?: string;
}
