//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Role } from './Role';

export interface Observation
{
	id: string;
	role: Role;
	registeredTime?: Date;
	sessionId: string;
	comment?: string;
}
