//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class ProtectiveEquipmentSettingTypeConstants
{
	public static BasicIsolationRoutines: string = `BASIC_ISOLATIONROUTINES`;
	public static ContactTransmission: string = `CONTACTTRANSMISSION`;
	public static DropletTransmission: string = `DROPLETTRANSMISSION`;
	public static AirborneTransmission: string = `AIRBORNETRANSMISSION`;
}
