//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class ProtectiveEquipmentSettingTypeConstants
{
	public static BasicInfectionControlRoutines: string = `BASIC_INFECTION_CONTROL_ROUTINES`;
	public static ContactInfection: string = `CONTACT_INFECTION`;
	public static DropletInfection: string = `DROPLET_INFECTION`;
	public static AirInfection: string = `AIR_INFECTION`;
}
