//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { OrganisationUnit } from "./OrganisationUnit";


export interface Session<TObservation>
{
	id: string;
	facilityId: number;
	facility: OrganisationUnit;
	department: OrganisationUnit;
	departmentId: number;
	unitId: number;
	facilityName: string;
	unit: OrganisationUnit;
	createdDate: Date;
	observations?: TObservation[];
	comment?: string;
}
