export class Urls {
  static LoginPageUrl = '';
  static HomePageForObservationUrl = 'register';
  static RegisterFiveIndicationsUrl = 'register/five-indications';
  static RegisterHandJewelryUrl = 'register/handJewelry';
  static RegisterGloveUrl = 'register/glove';
  static RegisterProtectiveEquipmentUrl = 'register/protectiveEquipment';
  static NotSentSessionsUrl = 'sessions/not-sent';
  static SentSessionsUrl = 'sessions/sent';
  static FiveIndicationsSessionUrl = 'sessions/five-indications';
  static HandJewelrySessionUrl = 'sessions/handJewelry';
  static GloveSessionUrl = 'sessions/glove';
  static ProtectiveEquipmentSessionUrl = 'sessions/protectiveEquipment';
  static SentFiveIndicationsSessionUrl = 'sessions/sent/five-indications';
  static SentHandJewelrySessionUrl = 'sessions/sent/handJewelry';
  static SentGloveSessionUrl = 'sessions/sent/glove';
  static SendProtectiveEquipmentSessionUrl = 'sessions/sent/protectiveEquipment';
  static ProfileUrl = 'profile';
}
