{{- if .Values.postgres.deploy -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "HyFive.fullname" . }}-db
  labels:
    {{- include "HyFive.dbLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: psql
      protocol: TCP
      name: psql
  selector:
    {{- include "HyFive.dbSelectorLabels" . | nindent 4 }}
{{- end }}
