apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "HyFive.fullname" . }}-observation
  labels:
    {{- include "HyFive.labels" . | nindent 4 }}
data:
  RedirectPagesSettings__RedirectLogInUri: {{ .Values.oidc.redirects.observation.login }}
  RedirectPagesSettings__RedirectLogOutUri: {{ .Values.oidc.redirects.observation.logout }}
  RedirectPagesSettings__LoggedOut: {{ .Values.oidc.redirects.observation.loggedout }}
  RedirectPagesSettings__LoggedIn: {{ .Values.oidc.redirects.observation.loggedin }}
