apiVersion: v1
kind: Service
metadata:
  name: {{ include "HyFive.fullname" . }}
  labels:
    {{- include "HyFive.labels" . | nindent 4 }}
spec:
  type: {{ .Values.observation.service.type }}
  ports:
    - port: {{ .Values.observation.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "HyFive.selectorLabels" . | nindent 4 }}
